### ISSUE TITLE
Meta: gsdx CRC hack level

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1575]
OpenGL is able to emulate various draw call correctly. Here a list of games that still have CRC hack enabled at the partial (aka openGL) level. Goal is to monitor/test which game still require a CRC even for openGL.

The hack magic can be found here https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSHwHack.cpp
- [x] Ace Combat 4 (hack has been moved to aggressive level as it introduces several new issues)
- [x] Alpine Racer 3 (hack has been removed as the underlying issue has been resolved)
- [ ] Black Hawk Down
- [x] Bleach Blade Battlers (hack has been moved to aggressive, can be used as a speed hack #2259)
- [ ] Burnout Dominator (depth handling issue, hack removes vertical bars from screen, still affects all hardware renderers)
- [ ] Burnout Revenge (same as Burnout Dominator)
- [ ] Burnout Takedown (same as Burnout Dominator)
- [x] Captain Tsubasa
- [ ] Crash Bandicoot: Wrath Of Cortex
- [ ] DBZ: BT2 (half screen bottom issue on PAL version by depth texture) last test Jan 2018
- [ ] DBZ: BT3 (half screen bottom issue on PAL version by depth texture) last test Jan 2018
- [ ] Devil May Cry 3
- [x] Eternal Poison
- [ ] Evangelion Jo (hack removes blur/glow to resolve ghosting when resolution is upscaled)
- [ ] FFVII: Dirge Of Cerberus (Hack removes garbage data rectangles appearing on screen when objects and characters (dis)appear)
- [ ] Fighting Beauty Wulong
- [x] Final Fight Streetwise
- [ ] Front Mission 5
- [ ] Genji
- [ ] Getaway (Removes fog wall in front of player, only works with the US version)
- [ ] Getaway: BlackMonday (same hack as The Getaway)
- [ ] Ghost in the Shell (channel effect not supported yet)
- [ ] God Hand
- [x] Haunting Ground (nearly perfect 264b764d6e8caebcf02dd945860df11f61feb592)
- [x] Heavy Metal Thunder
- [ ] Hummer Badlands
- [ ] Ikki Tousen
- [ ] Knights Of The Temple 2
- [ ] Kunoichi - last test Jan 2018
- [ ] Lord Of The Rings: Third Age
- [ ] Manhunt 2 (channel effect not supported yet)
- [x] Midnight Club 3
- [x] NanoBreaker (Shadow rendering issue has been resolved for OpenGL with blending, hack has been moved to Full, it removes shadows)
- [x] Narutimate Accel
- [x] Naruto
- [ ] Oneechanbara 2 Special
- [ ] Onimusha 3
- [x] Red Dead Revolver
- [x] ResidentEvil 4 (Hack removes the in-game fog, but this is rendered correctly now)
- [ ] Sacred Blaze
- [ ] Sakura Taisen
- [ ] Sakura Wars So Long My Love
- [x] Sengoku Basara
- [ ] Shadow of Rome
- [ ] Shin Onimusha
- [ ] Simple 2000 Series Volume 114
- [x] Soul Calibur 2 (Depth Emulation fixes the shadows - crc updated in #2256)
- [x] Soul Calibur 3 (Depth Emulation fixes the shadows - crc updated in #2256)
- [ ] Spartan
- [x] Star Wars Force Unleashed
- [ ] Steambot Chronicles
- [ ] Street Fighter EX3
- [x] Tales Of Legendia (???)
- [ ] Tales Of Symphonia
- [ ] TimeSplitters 2 (Removes 4-player overlay (which is visible even in single player modes) from screen, still affects all Hardware renderers)
- [ ] Tomb Raider Anniversary (broken texture cache garbage)
- [ ] Tomb Raider Legend
- [ ] Tomb Raider Underworld (broken texture cache garbage)
- [ ] Ultraman Fighting Evolution
- [ ] UrbanReign
- [ ] Wild Arms 4
- [ ] Wild Arms 5
- [x] Yakuza 2
- [x] Yakuza
- [ ] Zettai Zetsumei Toshi 2

**Comment by FlatOutPS2** [comment]
Alpine Racer 3 still needs it, as the issue affects all renderers(I do know a solution, though it might be a bit hacky).

**Comment by gregory38** [comment]
Ok. If you have some explanation of the issue it would be a nice addition.

**Comment by FlatOutPS2** [comment]
https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSRendererOGL.cpp#L700

If you add this if statement not just to the accumulation_blend, but in general it fixes the issue. A similar solution also works for DX9 and SW mode.

**Comment by FlatOutPS2** [comment]
The Burnout games are also stil necassary for all HW renderers. They still have have the vertical pillars on the screen without the CRC hack.

**Comment by woj1993** [comment]
What does CRC hack in Captain Tsubasa and DBZBD3? I always played Capitan Tsubasa without any CRC hack and didn't see any graphical errors.

**Comment by gregory38** [comment]
``` Captain Tsubasa ```
Dunno, it seems to remove the drawing of 1 framebuffer. Need to check the history. Likely useless

``` DBZBD3 ```
Complex CRC hack but actually most of it is already removed on the openGL level. I think this one is still active (need to search on the forum, or was it the DBZ2)

**Comment by gregory38** [comment]
For the record, the start of the outbreak ;)
https://github.com/PCSX2/pcsx2/commit/13df336966c08780f948b7e03add79c9037434d7

**Comment by FlatOutPS2** [comment]
> What does CRC hack in Captain Tsubasa and DBZBD3? I always played Capitan Tsubasa without any CRC hack and didn't see any graphical errors.

You do know that CRC hack means the CRC Hack Level in the GSdx Plugin Settings menu? If that's set to anything above none(or possibly minimal), the CRC hack is always on.

**Comment by Cobra84** [comment]
Turning it on at any level breaks more of Ace Combat 4 than it fixes. On fixes the weird ghosting effect, but removes the HUD in night missions.

**Comment by gregory38** [comment]
Ace combat gets 2 hacks actually. Maybe one can be removed. The ghost effect could be the blur comment. If someone can compile to test it, it would be nice.
```
		if(fi.TME && fi.FBP == 0x02a00 && fi.FPSM == PSM_PSMZ24 && fi.TBP0 == 0x01600 && fi.TPSM == PSM_PSMZ24)
		{
			skip = 71; // clouds (z, 16-bit)
		}
		else if(fi.TME && fi.FBP == 0x02900 && fi.FPSM == PSM_PSMCT32 && fi.TBP0 == 0x00000 && fi.TPSM == PSM_PSMCT24)
		{
			skip = 28; // blur
}
```

**Comment by FlatOutPS2** [comment]
I don't know what the clouds hack does, because the clouds are missing in HW regardless of CRC hack setting. 

The blur is fixed by the CRC hack. But as Cobra84 said, it causes issues with the HUD, though not just in night missions( see my test report: http://forums.pcsx2.net/Thread-Ace-Combat-Distant-Thunder-SCES-50410-E )

The ghost around the blur effect is resolved by setting blending unit accuracy to basic or higher.

But regardless of the blur, the entire plane of the player remains black regardless of CRC hack setting (see my issue on the bug: https://github.com/PCSX2/pcsx2/issues/1547 )

**Comment by FlatOutPS2** [comment]
The Getaway Black Monday is a complete cluster ****. It has effect on the cutscenes, but only seems to affect D3D modes. Turning CRC hack off makes the entire screen overly bright. setting it to Partial makes the screen turn green(and still too bright), and setting it to Full causes all kind of small opaque squares and white vertical lines appear over the effect, and the brightness is reduced too much(there is an effect during the cutscene to make the scene brighter, looks correct in SW).

With OpenGL HW the scene brightness sometimes appears correct, but there is a lot of flickering and a half-screen issue regardless of CRC setting...

**Comment by Cobra84** [comment]
Blending unit accuracy has no effect on missions where the HUD also disappears with the crc hack.

**Comment by MrCK1** [comment]
Doesn't GT4 use CRC for brightness hack; or was that only DX?

**Comment by FlatOutPS2** [comment]
> Blending unit accuracy has no effect on missions where the HUD also disappears with the crc hack.

BUA only removes the blurring. It doesn't affect anything else.

@MrCK1 GT4 isn't part of the checklist in the OP, as it has already been moved to the Full CRC level.

**Comment by Cobra84** [comment]
> BUA only removes the blurring. It doesn't affect anything else.

I meant that the BUA doesn't fix the blurring in the same missions that are affected by the crc hack. It works fine in missions where the crc hack worked too.

**Comment by FlatOutPS2** [comment]
Please move the ResidentEvil4 hack to Full level. The CRC hack removes the fog, without the hack the screen turns green with D3D,, but the fog emulates correctly on OGL with hardware depth.

**Comment by mirh** [comment]
Actually.. I think AC, should need an additional hack too. 
Clouds are "[tinier](http://www47.zippyshare.com/v/2NMSJEfJ/file.html)" in hw mode.

**Comment by FlatOutPS2** [comment]
Most clouds are actually invisible in HW in all AC games. The AC games need less hacks and more proper solutions. The current CRC hacks cause worse issues than they solve.

**Comment by mirh** [comment]
Isn't there like.. Just a single one? And only in AC4?
Indeed, I usually play with them disabled ("None") given I seem to gain some fps. 

Afaik AC only had [COP2](https://github.com/PCSX2/pcsx2/commit/35da3319dfb3f82f12135e9956b186a5f6f3e385) [patches](https://github.com/PCSX2/pcsx2/commit/1d5d9da25ba466f12afa568d43bcdb99f0d4a2d4).

**Comment by FlatOutPS2** [comment]
AC4 actually has two CRC hacks, and they both cause very annoying HUD issues. Anyway, a proper solution would probably work better than CRC hacks in this case.

**Comment by gregory38** [comment]
Could someone test those games
* FFVII DoC
* star wars force unleashed
* devil may cry 3
* eternal poison

**Comment by lightningterror** [comment]
I have a question regarding crc hacks , as the emulator gets more fixes every day crc hacks also need to be updated aka some need removing if they are no longer needed right ?

**Comment by lightningterror** [comment]
Resident Evil 4

Seems Direct3D doesn't require any crc hacks anymore. Tho I recommend moving them to Aggressive since having those effects not emulated provides a nice boost.

Comparison:

D3D
![pcsx2 2017-04-17 18-27-44-01](https://cloud.githubusercontent.com/assets/18107717/25095395/dc188f06-239b-11e7-8432-649efdc01885.jpg)

OpenGL
![pcsx2 2017-04-17 18-28-04-20](https://cloud.githubusercontent.com/assets/18107717/25095409/e83c6eb0-239b-11e7-90e3-9fd253a63a32.jpg)

The fog in the distance is related to Depth Emulation, similar to dbz bt3.

Upscaling causes pixel offsets but can be fixed with Wild Arms Offset hack.

**Comment by FlatOutPS2** [comment]
TimeSplitters 2 CRC hack removes 4-player overlay from screen. It affects all Hardware modes, but only OpenGL renders it properly.

![ts2](https://cloud.githubusercontent.com/assets/15942346/25183131/fc975f38-2516-11e7-8344-49db4aeb7bb7.jpg)

**Comment by 13xforever** [comment]
Sakura taisen has issues with opengl hw renderer, details are in #1919

**Comment by MrCK1** [comment]
@lightningterror This list has become somewhat outdated. Can you remove any of the CRC hacks from this last that you removed previously?

**Comment by lightningterror** [comment]
@MrCK1  DBZ BT3 still needs crc hacks for both renders.

> GT4 isn't part of the checklist in the OP, as it has already been moved to the Full CRC level.

And now it's on the Aggressive level since Texture cache has been updated.

**Comment by lightningterror** [comment]
Added Street Fighter EX3 to the list.
https://github.com/PCSX2/pcsx2/pull/2123

**Comment by marcoluc97** [comment]
Sorry to bother but this Issue can still be used to check if everything  is moved to GameDB and the related CRC hacks are purged?

**Comment by refractionpcsx2** [comment]
Most of these CRC hacks are actually coded in to test a bunch of stuff and aren't just toggling options on and off, those have already been moved.

**Comment by seta-san** [comment]
should this be closed? isn't crc gone?

**Comment by refractionpcsx2** [comment]
We still have CRC hacks, just not a level selection.

**Comment by lightningterror** [comment]
Closing as similar issue exists: https://github.com/PCSX2/pcsx2/issues/3568
