### ISSUE TITLE
Meta: MTVU compatibility issues

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#1669]
As with previous meta's. This doesn't mean we are working on this currently or that it will ever get fixed, this is more for information.  I just saw gregory's post on the forum about it so figured i'd make a start :P

Note: This is ONLY for broken games, right now, I consider slowdown and glitches a "tough" kind of situation. If you want a comprehensive list of those games, please visit the relevant forum thread here: http://forums.pcsx2.net/Thread-LIST-Games-that-may-not-work-well-with-MTVU

Fixed (As of Dec 2020):
- [x] 007: Agent Under Fire - (Internal slowdowns. Reported by Nobbs66) - Fixed in #4035 
- [x] 10,000 Bullets - (Black screen with MTVU. Reported by jackyyn) - Fixed in #4035 
- [x] Backyard Basketball - (Black screen with MTVU. Reported by junknaut) - Fixed in #4035 
- [x] Baroque - (Black screen on boot. Reported by Topken) - Fixed in #4035 
- [x] Brothers in Arms: Road to Hill 30 - (Broken. Reported by refraction) - Fixed at some point before 1.6
- [x] Crash Nitro Kart - (Broken. Reported by Coornio) - Fixed in #4035 
- [x] Def Jam: Fight for New York - (Hangs before title screen. Reported by indianchan) Fixed in #3971
- [x] DT Carnage - (Hangs on menu. Reported by CK1)
- [x] DT Racer - (Reports infinite loop Reported by refraction) Fixed at some point
- [x] Dog's Life - (Hangs before menu/gameplay, Reported by FlatOut) - Fixed in #3971 - Thrillville is probably fixed as well
- [x] FIFA series - (multiple issues, Reported by lightningterror, jesalvein, Ryudo, FlatOut) - Fixed in #3971
- [x] Fight Night Round 3 - (Crashes. Reported by shogunreaper) - Partially fixed in #3971, remaining issues fixed in https://github.com/PCSX2/pcsx2/commit/7b7278bc85fa3becd39c47168fe6c912523b4d43
- [x] Forever Kingdom (Crashes going in-game. Reported by CK1) - Fixed at some point.
- [x] Gradius V - (Black screen. Reported by billyash) - Fixed in #4035 
- [x] Grandia Xtreme - (Graphical glitches. Reported by jesalvein) - Fixed at some point.
- [x] Heatseeker - (Freezing, Reported by MartinBFFan #2322) - Fixed in #4035 
- [x] Hugo: Magic in the Trollwoods - (Hugo is brown and coins turn black. Reported by hoveringfoil) - Fixed at some point
- [x] James Bond 007: Everything or Nothing - (Internal slowdowns. Reported by CK1) - Fixed in #4035 
- [x] James Bond 007: Nightfire - (Crashes in driving missions. Reported by refraction) - Fixed in #3971
- [x] King's Field 4: The Ancient City - (Game doesn't load. Reported by CK1) - Fixed in #4035 
- [x] LUPIN III: Lupin la morte, Zenigata l'amore - (Reported by utente2012)
- [x] Marvel Ultimate Alliance - (Black screen on boot. Reported by vsub) - Fixed in #4035 
- [x] Medal of Honor Rising Sun - (Crashes at the first loading screen. Reported by Robbie207) - Fixed in #3971
- [x] MTV's Celebrity Deathmatch - (Won't boot with MTVU. Reported by Donovan24) - Fixed in #4035
- [x] NBA Street Vol. 2 - (Hangs. Reported by tegez) - Goes in-game in #3971, SPS fixed in https://github.com/PCSX2/pcsx2/commit/7b7278bc85fa3becd39c47168fe6c912523b4d43
- [x] Over The Hedge - (Hangs. Reported by Nicknine) Fixed at some point
- [x] Shrek 2 - (Broken graphics. Reported by CK1) - Fixed at some point
- [x] SkyGunner - (freeze loading missions/saving to memory card. Reported by CK1) - Fixed at some point
- [x] Sled Storm - (Black screen. Reported by GeoMan) - Partially fixed in #3971, remaining issues fixed in https://github.com/PCSX2/pcsx2/commit/7b7278bc85fa3becd39c47168fe6c912523b4d43
- [x] Summon Night Gran-These: Horobi no Ken to Yakusoku no Kishi - (Black screen. Reported by yxmline) - Fixed in #4035 
- [x] Thrillville - (Black screen. Reported by monsterjamp) - Fixed in #3971
- [x] TimeSplitters: Future Perfect - (Internal slowdown. Reported by NarooN) - Fixed in #4035 
- [x] TimeSplitters 2 - (Broken on load/ internal slowdown. Reported by refraction) - Fixed in #4035 
- [x] Tony Hawk series / Disney's Extreme Skate Adventure - (Hangs on loading. Reported by GeoMan, Catarax, refraction) - Fixed in #4035 
- [x] Wallace & Gromit in Project Zoo - (Reported by refraction) - Fixed in #3971
- [x] X-men Legends 2 - (Broken. Reported by Coornio) - Fixed in #4035 
- [x] Yu-Gi-Oh! Capsule Monster Coliseum - (Broken. Reported by Coornio) - Fixed in #4035 

Broken:
- [ ] Transformers / Transformers Armada: Prelude to Energon - (loading screens. Reported by Dreadmoth) - Filled buffer hang

Works but has issues:
- [ ] Sly Cooper 1-3 - ~~PCSX2 process doesn't die after close when MTVU is on.~~ Crashes randomly when loading a savestate(spam load for easier reproduction, triggered on Sly 2 US, last test 30.09.2021).

Please post any more you find below, or edit this post if you have access.

**Comment by gregory38** [comment]
Thanks you :+1:

**Comment by refractionpcsx2** [comment]
No problem :)

**Comment by FlatOutPS2** [comment]
If the list is only for broken games, why does it include slowdown and stuttering games?

A complete list for this issue would probably be over ten times the size it is now. It affects a lot of games.

**Comment by refractionpcsx2** [comment]
Stuttering is more severe than just making the game run slower, and those stutters could be seconds long or really quick ones, I can't tell just from that list, but it was under the "broken" section, so I'm taking it as that for now.  If it can be proven otherwise, I'll remove it.

As for the other 297 games, I'd appreciate it if you reported them ;)

**Comment by FlatOutPS2** [comment]
> As for the other 297 games, I'd appreciate it if you reported them ;)

As I said I don't use the hack, so I don't keep track of it. But if you check the list you might notice it contains a lot of EA games. It's just not FIFA 10 and NBA Street, but many more games from those series and their counterparts from the other sports.

**Comment by refractionpcsx2** [comment]
If that's the case, they likely use the same engine, so fixing those will fix the others, so not a huge issue that they're missing :)

**Comment by FlatOutPS2** [comment]
> If that's the case, they likely use the same engine, so fixing those will fix the others, so not a huge issue that they're missing :)

They're similar engines, not always the same. IIRC the issues affects most PS2 FIFA games, even though they use 3 different engines. But wouldn't fixing the issue resolve it for all games regardless of engine or is it cluster of issues?

**Comment by refractionpcsx2** [comment]
> But wouldn't fixing the issue resolve it for all games regardless of engine or is it cluster of issues?

That's what I was saying, fixing one (or all listed) will more than likely fix the other games.  The likelyhood is they all use a similar library to do something, which is what is causing MTVU to keel over, so hopefully fixing that will fix all those games.

**Comment by willkuer** [comment]
I always thought that the MTVU hack purposely misses some implementations to make the threading possible/reasonable. I though the communication is from or two VU is only one way using MTVU and bidirectional for single threaded VU. I think something like that was written in the blog by cotton.

**Comment by refractionpcsx2** [comment]
possibly, but this is stuff not caused by read backs.  In fact read backs are done and possible, just it's really slow.  This is games that just outright refuse to work, but we haven't looked in to them to see if it's an MTVU bug or an impossibility.

**Comment by lightningterror** [comment]
For "Fifa Street" with mtvu on after the loading screen the screen goes black and VU is at 100%. pcsx2 doesn't respond and it needs to be forcefully closed.

The only time mtvu works is on the menus after the loading screen. During loading or actual gameplay it doesn't.

I hope this info helps.

**Comment by refractionpcsx2** [comment]
Thanks, I'll update the entry :)

**Comment by FlatOutPS2** [comment]
Like I said, EA (sports) games. You can basically add all FIFA games.

**Comment by refractionpcsx2** [comment]
Like I said, they probably all act in the same way.

**Comment by FlatOutPS2** [comment]
So adding them one by one isn't useful either. :p

**Comment by refractionpcsx2** [comment]
I didn't, I modified one of them, the others are only there because I copy/pasted the list :P

**Comment by FlatOutPS2** [comment]
No, it looks worse now. :p

**Comment by refractionpcsx2** [comment]
Then you fix it ;)

**Comment by lightningterror** [comment]
The fifa one is wrong , It should be "mtvu works only on menus"

**Comment by lightningterror** [comment]
"FIFA series (multiple) (Won't boot with MTVU, crashes during gameplay, does work in menu's and loading screens. Reported by lightningterror, jesalvein, Ryudo, FlatOut)"

It should be it doesn't work on loading screens as well.

**Comment by Catarax** [comment]
You can add:
- Disney's Extreme Skate Adventure
- Tony Hawk's Underground 2
- Tony Hawk's Project 8
- Tony Hawk's Downhill Jam

Loading screen broken

**Comment by refractionpcsx2** [comment]
> "FIFA series (multiple) (Won't boot with MTVU, crashes during gameplay, does work in menu's and loading screens. Reported by lightningterror, jesalvein, Ryudo, FlatOut)"
> 
> It should be it doesn't work on loading screens as well.

screw it, i've just shortened it to just list the game



> You can add:
> 
> Disney's Extreme Skate Adventure
> Tony Hawk's Underground 2
> Tony Hawk's Project 8
> Tony Hawk's Downhill Jam
> Loading screen broken

Thanks, added :)

**Comment by Dreadmoth** [comment]
_Transformers_ / _Transformers Armada: Prelude to Energon_ crashes on loading screens if MTVU is enabled.

(Boots fine. Main menu and intro movie work without issues. Actual gameplay seems fine as well, however MTVU doesn't seem to improve performance).

**Comment by refractionpcsx2** [comment]
Added, thank you :)

**Comment by MonJamp** [comment]
Something to note about Thrillville: There's minigames you can play straight from the main menu. Playing a 2D minigame works fine with MTVU enabled. It's only 3D games/portions that cause a black screen with MTVU enabled.

Also just enabling MTVU causes this warning to repeat itself:
```
yo
yo
yo
yo
yo
----
microVU1: BAL in BAL delay slot! [29a0]  - If game broken report to PCSX2 Team
Found BAL in delay slot, linking - If game broken report to PCSX2 Team
```

And when entering a 3D portion I get warnings like these:
```
microVU1 Warning: Branch, Branch, Branch! [2930]
Gif Unit - GS packet size exceeded VU memory size!
```

Don't know if this is helpful at all but clearly MTVU is doing something really weird with this game.

**Comment by refractionpcsx2** [comment]
Do you not get the "yo"'s if MTVU is disabled? that's strange, you should still get them!

**Comment by MonJamp** [comment]
Yeah, the `yo`'s don't appear with MTVU disabled.

**Comment by refractionpcsx2** [comment]
That's very strange, that almost says that MTVU is changing the VU program, that can't be right :/

**Comment by MrCK1** [comment]
Add DT Carnage here. The graphics are another story...

**Comment by MrCK1** [comment]
@refractionpcsx2 Fight Night Round 3 can be removed; it's not an MTVU issue but a MicroVU issue with GIF Packet overflow. SuperVU prevents a crash.

**Comment by refractionpcsx2** [comment]
@MrCK1 so it even crashes with MTVU disabled?

**Comment by MrCK1** [comment]
No it works fine with MTVU enabled, but it needs SuperVU recompiler to avoid the crash. MicroVU will crash regardless of rounding.

**Comment by refractionpcsx2** [comment]
You realise MTVU only works with microVU right?

So just to be clear it still crashes in microVU with MTVU off?

**Comment by MrCK1** [comment]
@refractionpcsx2 Sorry for the confusion. It doesn't crash with MTVU off. You can leave it in the list.

**Comment by MrCK1** [comment]
Added another 007 title, Everything or Nothing.

**Comment by MrCK1** [comment]
I added "King's Field 4: The Ancient City" according to the wiki entry here: https://wiki.pcsx2.net/King%27s_Field:_The_Ancient_City

**Comment by MrCK1** [comment]
Added "Over the Hedge"

**Comment by MrCK1** [comment]
Updated the meta list to reflect a number of games that now work properly with MTVU thanks to the latest changes by @refractionpcsx2

**Comment by MonJamp** [comment]
Just tested Thrillville, it used to crash when entering 3D parts of the game (when MTVU is enabled) but it's fixed now 👍

**Comment by MrCK1** [comment]
> 
> 
> Just tested Thrillville, it used to crash when entering 3D parts of the game (when MTVU is enabled) but it's fixed now 👍

Thanks, I moved it up.

**Comment by refractionpcsx2** [comment]
With the merging of #4035, the list is looking pretty good :) Please continue to post more if any are found though.

**Comment by atomic83GitHub** [comment]
The game "Dear Boys: Fast Break!" doesn't technically break with MTVU but there is a consistent gif handler console spam with it on.

<img width="333" alt="Capture" src="https://user-images.githubusercontent.com/26351275/116791505-17cf4d00-aabb-11eb-93a8-d2890b81f284.PNG">

**Comment by atomic83GitHub** [comment]
Time Crisis 2 - Speed loss when using MTVU with booth EE and VU1 threads being bound at the same time.

**Comment by coornio** [comment]
Midnight Club 3 (DUB/DUB Remix included I suppose) does not run well in 1.7 dev with MTVU enabled. Internal framerate presumed to fall to sub-15 frames, despite the OSD reporting full fps and the percentages being acceptable. Plays much better with Instant VU1 enabled instead, will be too easily EE-limited without it.

For the record only, testing on 1.6 stable showed that the old MTVU implementation ran very well. When uncapped, the game plays at roughly 1.7x to 1.8x the speed it gets on 1.7 dev. Assumed to be the result of emulation accuracy increases since 1.6 stable, but mentioning it regardless in the event that it becomes important later on (as in thinking something might be wrong).

**Comment by refractionpcsx2** [comment]
> Midnight Club 3 (DUB/DUB Remix included I suppose) does not run well in 1.7 dev with MTVU enabled. Internal framerate presumed to fall to sub-15 frames, despite the OSD reporting full fps and the percentages being acceptable. Plays much better with Instant VU1 enabled instead, will be too easily EE-limited without it.
> 
> For the record only, testing on 1.6 stable showed that the old MTVU implementation ran very well. When uncapped, the game plays at roughly 1.7x to 1.8x the speed it gets on 1.7 dev. Assumed to be the result of emulation accuracy increases since 1.6 stable, but mentioning it regardless in the event that it becomes important later on (as in thinking something might be wrong).

Please be clear about when you're talking about the internal or emulator framerate, as the 1.7x you mentioned to me was emulator framerate not the internal framerate. I'm more interested in the framerate when locked with the framelimiter.

**Comment by JordanTheToaster** [comment]
Nascar 07 totally locks up with MTVU enabled on Nightly 1.7 2088.

![image](https://user-images.githubusercontent.com/80843560/144248858-161e6bc8-ba25-4db8-bfce-04ff75e5df96.png)

**Comment by refractionpcsx2** [comment]
You sure it's only with MTVU? Because it's the MTGS thread which seems to be stuck in a loop.

**Comment by JordanTheToaster** [comment]
> You sure it's only with MTVU? Because it's the MTGS thread which seems to be stuck in a loop.

It only happens when MTVU is enabled.
