### ISSUE TITLE
Meta: Games with IPU issues

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#2132]
I figured a meta issue to track games with various IPU issues would be helpful since they're not always well documented/found easily. FMV issues related to GSdx are not included here.

Feel to make corrections as necesssary. The games here are based off my own tests, and data from the wiki, so re-tests would always be nice.

- [ ] Test Drive (in-game freezing) - https://github.com/PCSX2/pcsx2/issues/1863

- [ ] Call of Duty World at War: Final Fronts (corruption)

- [ ] Harry Potter Quidditch World Cup (corruption)

- [ ] James Bond 007: Everything or Nothing

- [ ] Black & Bruised (hangs without SkipMpeg)

- [ ] The Guy Game

- [ ] The Incredible Hulk (hangs without SkipMpeg)

- [ ] Test Drive Off-Road: Wide Open (blank videos, might be GSdx issue instead?)

- [ ] Tiger Woods PGA Tour 06 (hangs without SkipMpeg)

- [ ] Q-Ball Billards Master (unsure if this one has issues still, may be fixed)

- [ ] Classic British Motor Racing (hangs without SkipMpeg)

- [ ] Knight Rider: The Game (hangs without SkipMpeg)

Unconfirmed:

- [ ] Spyro: A Hero's Tail - https://github.com/PCSX2/pcsx2/issues/858

- [ ] Guitar Hero - https://github.com/PCSX2/pcsx2/issues/2108 (freezes at end of videos)

- [ ] Valkyrie Profile 2: Silmera - https://github.com/PCSX2/pcsx2/issues/1634 (freezes at end of videos)

**Comment by atomic83GitHub** [comment]
You can add Onimusha - Dawn of Dreams, it have some corruption in opening/title screen and have a patch to avoid some IPU issues.

**Comment by atomic83GitHub** [comment]
I have update my GameDB PR with games that need skipmpeg to work. Also you can add "lethal skies 2" and "Paris dakar rally".

**Comment by atomic83GitHub** [comment]
Only Paris-Dakar and lethal skies 2 booth pal.

**Comment by MrCK1** [comment]
Oh you're right about the Hulk. I'll remove that then.

**Comment by atomic83GitHub** [comment]
Hum, you are right with lethal skies 2, I have test it on the 1.4 version but it work just fine in 1.5dev, unfortunatly, paris dakar is still broken.

**Comment by atomic83GitHub** [comment]
You can add "twisted metal head on extra twisted edition" wich have some fmv corruption (can be solve using EEcyclerate to -3 but this will cause stuttering issue).

**Comment by MrCK1** [comment]
@atomic83GitHub Can you upload blockdumps during an IPU segment of the games you own here?

**Comment by atomic83GitHub** [comment]
So I have Lethal Skies II, Paris Dakar and Guitar Hero (I have not Onimusha at the moment because it is a friend game), I did Blockdump on these but this issue happen in booth of them :(https://github.com/PCSX2/pcsx2/issues/2266 , I will try the linuz cdvd plugin

**Comment by MrCK1** [comment]
@FlatOutPS2 Here's a blockdump for Harry Potter, I'll get the others and modify this post accordingly.

[HP_QWC_ipublockdump.zip](https://github.com/PCSX2/pcsx2/files/1629827/HP_QWC_ipublockdump.zip) (rename to .7z)

**Comment by FlatOutPS2** [comment]
@atomic83GitHub @MrCK1 Can either of you upload a (linuz cdvd) blockdump of one of the "hangs without SkipMpeg" games. I might look into this on the weekend.

**Comment by atomic83GitHub** [comment]
Here is the Guitar Hero dump, Paris arrive next.
https://drive.google.com/file/d/104wWmm_pOauFI1HzIeYKfdRY2leVPqSg/view?usp=sharing

**Comment by FlatOutPS2** [comment]
The guitar hero dump is still not working. It now prints `Block ... not found in dump` instead of showing the FMV. I guess a succesful dump of this game won't be possible.

**Comment by atomic83GitHub** [comment]
Hum, I have a demo disk wich sometimes fail to read the FMV's (like Spyro), would you want a Blockdump on it?

**Comment by atomic83GitHub** [comment]
I will do the Blockdump when I back home, also it's the SCEE hits demo [SCED-52970].

**Comment by FlatOutPS2** [comment]
> it's the SCEE hits demo [SCED-52970].

I have this demo. But it doesn't have a Spyro FMV? See: https://wiki.pcsx2.net/SCEE_Hits_Demo

**Comment by atomic83GitHub** [comment]
No, you probably misunderstood me :). I was just saying that this demo seems to do the same issue as the Spyro game :).

Also, I found some games that have a custom IPU patch in the DB:

![capture](https://user-images.githubusercontent.com/26351275/35223315-2e7b0366-ff81-11e7-84e6-ea1ad0d76055.PNG)

![capture2](https://user-images.githubusercontent.com/26351275/35223323-339e4cfe-ff81-11e7-8977-b25a758249fb.PNG)

![capture3](https://user-images.githubusercontent.com/26351275/35223326-36348064-ff81-11e7-8255-f6e57a9a3769.PNG)

![capture5](https://user-images.githubusercontent.com/26351275/35223327-381862c4-ff81-11e7-834e-8673261355b8.PNG)

![capture6](https://user-images.githubusercontent.com/26351275/35223329-39a3ced0-ff81-11e7-9514-717de1515ce9.PNG)

![capture7](https://user-images.githubusercontent.com/26351275/35223330-3b370d52-ff81-11e7-926b-fd36ab54d257.PNG)

**Comment by FlatOutPS2** [comment]
> No, you probably misunderstood me :). I was just saying that this demo seems to do the same issue as the Spyro game :).

Oh, right. So does it fail the same as the Spyro issue too, 40% chance of failing. and returns to main menu straightaway?

I know about some of those other games. F1 2001 should be fine without the patch now, and Tekken 4 could be related(seemed like it when I tested the FMV). Dakar 2(it's not called Paris-Dakar 2) is probaly the same issue as the original game.

**Comment by atomic83GitHub** [comment]
@FlatOutPS2, yes, this is the issue I was talking about.

**Comment by MrCK1** [comment]
@FlatOutPS2 Does the blockdump from Harry Potter work? Just making sure ;)

**Comment by FlatOutPS2** [comment]
Yes, it seemed to work as it should. The corruption is very, very bad though, I couldn't even tell if the FMVs ended early or not. I assume it's the same on the real game?

**Comment by MrCK1** [comment]
Not sure if you had noticed while playing the blockdump, but the game's logging is very verbose. I'll look again, but I'm not 100% positive if the FMVs are actually ending early or not.

**Comment by FlatOutPS2** [comment]
@atomic83GitHub I tried the SCEE Hits Demo FMVs, and they all worked without fail over several runs.

**Comment by atomic83GitHub** [comment]
I will try the @turtleli PR for Guitar Hero, I will post the results here.

**Comment by FlatOutPS2** [comment]
@MrCK1 Are there any other games in the top list which are untested? If so, you should move those to the unconfirmed list.

**Comment by atomic83GitHub** [comment]
Nope, still doesn't work.

**Comment by MrCK1** [comment]
I updated the list and moved a few to unconfirmed. I'll have to check Guitar Hero later, as I said before I never got it to freeze consistently - it could be an issue with a specific region of the game.

**Comment by MrCK1** [comment]
@prafullpcsx2 Can you see if videos in Dino Stalker still hang at the end? Thanks.

**Comment by prafullpcsx2** [comment]
@MrCK1 Dino stalker video hangs were fixed long time ago. I retested the game today and can confirm the videos don't hang.

**Comment by FlatOutPS2** [comment]
@MrCK1 Did you test Black& Bruised yourself? @prafullpcsx2 once mentioned it was fixed years ago: https://github.com/PCSX2/pcsx2/pull/1507#issuecomment-241102750

**Comment by MrCK1** [comment]
I took that one from the wiki, didn't test it myself. The last test case there is older.

**Comment by FlatOutPS2** [comment]
@prafullpcsx2 Does Crashed still freeze without the patch? If so can you upload a block dump of the issue?

**Comment by MrCK1** [comment]
Added Dropship United Peace Force as noted in https://forums.pcsx2.net/Thread-Core-Bug-Report-Dropship-United-Peace-Force-NTSC?pid=580678#pid580678

**Comment by FlatOutPS2** [comment]
> Added Dropship United Peace Force as noted in https://forums.pcsx2.net/Thread-Core-Bug-Report-Dropship-United-Peace-Force-NTSC?pid=580678#pid580678

@MrCK1 Can you make a blockdump of the issue?

**Comment by rcaridade145** [comment]
By looking at the source of Play! and PCSX2, PCSX2 on read32 seems does not cover 2 cases that Play! covers `case IPU_TOP + 0x0:
		if(!m_isBusy)
		{
			unsigned int availableSize = std::min<unsigned int>(32, m_IN_FIFO.GetAvailableBits());
			//If no bits are available, return zero immediately, shift below won't have any effect
			if(availableSize == 0) return 0;
			uint32 result = m_IN_FIFO.PeekBits_MSBF(availableSize);
			result <<= (32 - availableSize);
			return result;
		}
		else
		{
			return 0;
		}
		break;

	case IPU_TOP + 0x4:
		{
			//Not quite sure about this... are we really busy if there's no data in the FIFO?
			//This was needed to fix Timesplitters
			unsigned int availableSize = std::min<unsigned int>(32, m_IN_FIFO.GetAvailableBits());
			return GetBusyBit(m_isBusy) | GetBusyBit(availableSize != 32);
		}
		break;`

**Comment by MrCK1** [comment]
Added "Shox" to the list, corruption looks the same as Harry Potter: QWC - nice verbose output too. Anyways, I'll upload a blockdump when I get around to it.

**Comment by lightningterror** [comment]
Likewise with this one, switching it with 1.8

**Comment by refractionpcsx2** [comment]
Marked Arctic Thunder as fixed by #3877

**Comment by seta-san** [comment]
myst 3.. although a patch was released..

**Comment by RedDevilus** [comment]
Sims bustin out: In the past needed the skip mpeg but now it has corrupted sprites at the end of the starter FMV (after the couple drives away on the beach). I doubt many will notice it.
![image](https://user-images.githubusercontent.com/24227051/109223572-0ddb5600-77bb-11eb-9b20-66bfbad06cf4.png)

**Comment by JordanTheToaster** [comment]
Conflict: Desert Storm 2 PAL has extremely bad flickering in FMVs.

**Comment by refractionpcsx2** [comment]
Thanks for the information, that's very interesting :) I still have no idea how to fix it lol

**Comment by JimScript** [comment]
Jimmy Neutron - Boy Genius needs Skip MPEG Hack to get to the start menu, otherwise it _HARD_ crashes the emulator after the last video. With the hack it does get there but with no start screen visible, but after pressing the start button everything is normal and FMVs play without issue. Log: [emulog.txt](https://github.com/PCSX2/pcsx2/files/8800900/emulog.txt)

**Comment by refractionpcsx2** [comment]
With the introduction of @Goatman13 's start code changes, Tales of Rebirth video seems to get out of sync and start glitching (the one after the main menu), the startcodes seem to become junk, but it worked fine on the old code.

![image](https://user-images.githubusercontent.com/6278726/171627385-28679e3d-d025-4e36-b6ef-3c84af890bd1.png)

**Comment by refractionpcsx2** [comment]
> Jimmy Neutron - Boy Genius needs Skip MPEG Hack to get to the start menu, otherwise it HARD crashes the emulator after the last video. With the hack it does get there but with no start screen visible, but after pressing the start button everything is normal and FMVs play without issue.

underclocking the EE to the lowest setting seems to get around the crash, but it's hit and miss if the menu looks screwed or not.

**Comment by ScottNash042** [comment]
7 Blades 
still happening on v2.7.10
