### ISSUE TITLE
Meta: Games with VU m-bit issues

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#2294]
Currently this doesn't work properly, the issue being is on the PS2 the EE should be stalling waiting for VU0 to reach an "M" bit, but because we run the VU's instantly, this never happens, so my only vague solution was to stall the VU's once it hits an m-Bit then pick it up again later when the EE is ready.

Please check out the branch called pcsx2-mbit which improves the graphics on the following games (except where noted), if you can improve it further, any help would be greatly appreciated!

Known games affected (ticked are fixed in branch):
- [x] Crash Twinsanity (was working with the original implementation however, hangs on branch)
- [x] Gungrave (works on original implementation, hangs on branch)
- [ ] Marvel Nemesis: Rise of the Imperfects - Issues unrelated to m-bit
- [x] Mike Tyson's Heavyweight Boxing
- [x] My Street
- [x] Totally Spies! Totally Party
- [x] Hot Shots Golf 4 (works on master branch, hangs on the pcsx2-mbit branch)
- [x] Star Ocean 3 - the background on the main menu is missing
- [x] Wakeboarding Unleashed featuring Shaun Murray - slightly more SPS - works on master but waves missing due to another VU/VIF timing problem
- [x] Sprint Cars 2 - Showdown at Eldora (hangs on m-bit branch)
- [ ] World series baseball 2K3 - Issues unrelated to m-bit

Games possibly affected
- [x] Metal Gear Solid 2 - needs to be tested on m-bit branch
- [x] Amplitude

Unaffected games
- [x] Metal Gear Solid 3 - works fine with no problems on both master and m-bit branches
- [x] Valkyrie Profile: Silmeria cutscenes
- [x] "Find My Own Way" demo
- [x] Urban Reign
- [x] Black

If you know of any other games that show "m-bit set" in the console window please post them here, especially if they're broken.

**Comment by MrCK1** [comment]
@refractionpcsx2 I added Hot Shots Golf 4 to the list, which also hangs on this branch. 

```
microVU0: Cached Prog = [005] [PC=05d8] [List=01] (Cache=0.030%) [0.0mb]
microVU0: pState's cFlag Info was expected to be set [05d8]
microVU0: pState's cFlag Info was expected to be set [05e8]
microVU0: M-bit set! PC = 618
microVU0: M-bit set! PC = 620
microVU0: M-bit set! PC = 628
microVU0: M-bit set! PC = 630
microVU0: M-bit set! PC = 638
microVU0: M-bit set! PC = 640
Mbit on CondBranch
microVU0: Cached Prog = [006] [PC=0638] [List=01] (Cache=0.035%) [0.0mb]
microVU0: M-bit set! PC = 638
microVU0: M-bit set! PC = 640
Mbit on CondBranch
microVU0: M-bit set! PC = 638
microVU0: M-bit set! PC = 640
Mbit on CondBranch
```

**Comment by refractionpcsx2** [comment]
Thanks :)

**Comment by FlatOutPS2** [comment]
Oh-no, another branch on the master... 😛  Seriously though, there are way too many. I recently had trouble finding an old branch on my fork because of it.

So the VUs running instantly is the actual issue here?

**Comment by refractionpcsx2** [comment]
Yeah well blame gregory for that one, I think most of them are his :P

Yeah that's pretty much the crux of it, it looks like developers are assuming the EE is going to be ahead of the VU's, then waits for an M flag before writing a new value (it copies a value in to the VU's to be used in a calculation in the near future).

TBH it's going to be a bitch to get right, it may require a complete overhaul of the VU cycling so it stays in sync with the EE, right now it runs for like 5000 cycles on startup, then each run it gives itself another 4000 or something, it's all over the place.

**Comment by prafullpcsx2** [comment]
@refractionpcsx2 : I am testing some games now. This looks very promising. By the way sorry for being off topic but what about games that throw microVU0: T-bit set! message?

**Comment by refractionpcsx2** [comment]
Those should be working, at least as far as the T-bit bit goes :p

**Comment by MrCK1** [comment]
T-bit and D-bit had no problems for me. At least the M-bit seems to be rarely used. The only people to take advantage of it are those were taking advantage of both VUs, which was usually Sony's dev teams.

**Comment by prafullpcsx2** [comment]
I asked because Spiderman 3 throws this message right before it's usual hang point at the start of level 2

microVU0: 2 cycle stall on branch instruction [0018]
microVU0: T-bit set! PC = 490
microVU0: Cached Prog = [001] [PC=0498] [List=01] (Cache=0.024%) [0.0mb]

**Comment by MrCK1** [comment]
That reminds me, I checked Spiderman 3 with a debugger a while ago. It hangs here IIRC. I'm 99% positive it was this line:

https://github.com/PCSX2/pcsx2/blob/c2587abcea76b8daec96f18fe51a43512c579605/pcsx2/x86/microVU_Compile.inl#L696

**Comment by refractionpcsx2** [comment]
That's moved past the T-bit part before it hangs I would say, but I can look in to it.

**Comment by trostboot** [comment]
Nothing visibly changes for Valkyrie Profile: Silmeria based on two quick looks at two cutscenes where M-bit pops up.

**Comment by trostboot** [comment]
Anything specific to test for in Star Ocean 3? I did some running around various areas and triggered some cutscenes (seems m-bit mostly pops up here, like with VP2) and there wasn't anything out of the ordinary, but if you know of some specific problematic sections of the game, I'd be happy to take a closer look.

**Comment by refractionpcsx2** [comment]
You don't need to test star ocean 3 as I've already tested it. The only symptom is the background on the main menu is missing

**Comment by atomic83GitHub** [comment]
I suspect that the game "Black" have serious issue with M-bit handling because I found something interesting, as I said, at the end of the level 4, the game is completely broken, I just seen that when the game do these issue, the console show this:

![capture](https://user-images.githubusercontent.com/26351275/36307781-f817c6be-131d-11e8-927e-ecec6d039689.PNG)

I will post a savestate of that place.

**Comment by refractionpcsx2** [comment]
What is the game like with my branch?

**Comment by atomic83GitHub** [comment]
Exactly the same as the master branch.

**Comment by refractionpcsx2** [comment]
Okay, it may not be the mbit stuff then, might be a red herring, but will keep it in mind

**Comment by MrCK1** [comment]
The "Find My Own Way" demo uses the M-Bit but its' status is unchanged, still as slow as ever.

**Comment by refractionpcsx2** [comment]
Is it just slow or are there graphics issues also?

**Comment by MrCK1** [comment]
There's no graphical issues, it just becomes very slow internally when it reaches these "spikes"

![gsdx_20180324203425](https://user-images.githubusercontent.com/16314399/37870380-c0d25dda-2fa2-11e8-9680-6a82e5eb0a48.png)

**Comment by refractionpcsx2** [comment]
I'm guessing it's still as slow in software mode? just to rule out the GS :P

**Comment by MrCK1** [comment]
Yep, just as slow. My comment before about the spikes is unrelated, it never recovers to full speed after a certian point. It has issues with audio stutter as well.

**Comment by refractionpcsx2** [comment]
Okay. I'm not totally convinced it is the same issue as I'd only expect graphical errors with this, but I guess it doesn't hurt to keep an eye out.

**Comment by MrCK1** [comment]
This branch breaks Gungrave, can't reach the title screen.

**Comment by MrCK1** [comment]
Added Black. Game is unaffected by changes in the branch

**Comment by atomic83GitHub** [comment]
I have good news for "Black", the Mbit branch actually solve the level 4  issue! However there are still collision issues everywhere but now, you can complete the level 4 without screen spinning and game hanging on flashing colors (note: old savestates does not work).

This is the problem that happen in master branch (at 39.57)
https://www.youtube.com/watch?v=yKYueREUlJY

**Comment by MrCK1** [comment]
@atomic83GitHub Do you know if it is related to #2884 ?

**Comment by atomic83GitHub** [comment]
No it's not related, the "hanging with flashy colors" is a another problem which happened only in level 4 (in this big room).

**Comment by atomic83GitHub** [comment]
You can add World series baseball 2K3

**Comment by atomic83GitHub** [comment]
You can add: ESPN major league baseball 2k4 (have crashing and graphics problems)

And: Okage Shadow King (works fine with booth master and Mbit branches)

**Comment by atomic83GitHub** [comment]
Find my own way is broken, Mbit ops murder the graphics of that demo (The performance is a another story)

@MrCK1 Look you screenshot compared to the real PS2:

![image](https://user-images.githubusercontent.com/26351275/58728734-d4a86300-83e7-11e9-8ec7-fa4e5218782b.png)

![image](https://user-images.githubusercontent.com/26351275/58728875-294bde00-83e8-11e9-947f-5f5fe3562f49.png)

**Comment by refractionpcsx2** [comment]
Fair enough! I think I went the wrong way about this change anyway, so if I revisit this I'll probably do it another way

**Comment by refractionpcsx2** [comment]
Closing this ass the mbit related issues are now resolved, the other remaining issues are due to VU timing issues which are outside the scope of this meta.
