### ISSUE TITLE
Meta: Games that require an alternate SPU2 DelayCycles value

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#2371]
This issue is a list of games that require a modified DelayCycles value in order for sound to work properly. It will be a good reference for the future.

MK:DA and FFBA have been broken since this[ build](https://github.com/PCSX2/pcsx2/commit/f1cffa6f7fd8e85a2d2df35b7c18ca2e4d3606ab#diff-880fcba486dd038bdc85976ae1e9297a), the others here may be the same.

- [ ] Armored Core - https://github.com/PCSX2/pcsx2/issues/2917
- [ ] Fatal Fury Battle Archives Vol. 2 (US:NTSC) - (DelayCycles 0/1)
- [ ] Mortal Kombat: Deadly Alliance (PAL) - not always necessary (DelayCycles 0/1)
- [ ] Unreal Tournament (NTSC-U) - (works with DelayCycles 3 or lower)
- [ ] Higurashi no Naku Koro ni Matsuri Kakera Asobi (#918)

Unconfirmed:
- [ ] Spiderman 2
- [ ] Deus Ex: The Conspiracy (#615)

**Comment by seta-san** [comment]
This issue belongs in here too
https://github.com/PCSX2/pcsx2/issues/268

**Comment by refractionpcsx2** [comment]
Should be all fixed in #3959
