### ISSUE TITLE
Meta: Upscaling Issues

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2860]
Meta issue of upscaling issues to avoid creating duplicate issues.
Many of these issues can/are solved with a workaround. Usually TC offset or crc hacks.
Upscaling code can also be improved.

- [ ] Gran Turismo 4: Resolution upscale https://github.com/PCSX2/pcsx2/issues/1796 (workaround TC X Y offsets)
- [ ] GTA https://github.com/PCSX2/pcsx2/issues/2729
- [ ] Graphical Corruption in Valkyrie Profile 2: Silmeria https://github.com/PCSX2/pcsx2/issues/1809
- [ ] God of War II : Vertical lines under water and in hell https://github.com/PCSX2/pcsx2/issues/2533 (Workaround crc hack or HPO special + Align Sprite)
- [ ] Midnight Club https://github.com/PCSX2/pcsx2/issues/2729
- [ ] Ratchet: Deadlocked https://github.com/PCSX2/pcsx2/issues/2984
- [ ] ~~San Andreas Radiosity - Upscaling offsets https://github.com/PCSX2/pcsx2/issues/2525~~
- [ ] Soul Calibur 2 (JP) intro underline https://github.com/PCSX2/pcsx2/issues/2852
- [ ] Sprite Scaling Problem https://github.com/PCSX2/pcsx2/issues/900
- [ ] Tales of the Abyss - ghosting/upscaling https://github.com/PCSX2/pcsx2/issues/2221
- [ ] Tekken 5 with Distorted(Garbage) Graphics https://github.com/PCSX2/pcsx2/issues/638 (Workaround crc hack)
- [ ] Zombie Hunters 2: misaligned bloom at native resolution with OGL HW https://github.com/PCSX2/pcsx2/issues/2007

There are many other games that are not on this list that have issues, some with crc hack workarounds. This just covers the opened github issues.

**Comment by mirh** [comment]
Seriously, you should check a doctor for this OCD with pending issues. 
I don't pretend to have any specific technical insight into any of these, but every one of them seems independent of the others (let alone #2852 which as I was saying, looks like a problem with the source material itself, not even *rendering*). 

Perhaps this ticket may help discovering some generalizable common pattern, and it would be nice, but until then it should be thought as an addition to the original troubles, not a replacement not even proved to exist

**Comment by Hecklezz** [comment]
Would like to add to the list Dynasty Warriors 4 and 5 (and pretty sure their expansions). They have multiple verticle 'tears' when using anything except native resolution. I have personally tried to fix it to no avail using different pcsx2 settings and offsets.

**Comment by atomic83GitHub** [comment]
You can add every games that use a "HDR" lighting system such as "Dora the Explorer - To the Purple Planet" and "The Incredibles".

**Comment by RedDevilus** [comment]
Issue is not being used since 2019 and is increasingly handled with the GameDB and other improvements.
