### ISSUE TITLE
FBW-based Screen Clear Issue

### ISSUE THREAD

**Issue by tadanokojin** [PCSX2/pcsx2#3180]
**Games Tested:**
- [x] Evil Dead: Fist Full of Boomstick ([dump](https://dumps.pcsx2.net/index.php/s/6gmFTEzojKDixfr))
- [x] Tom And Jerry: War of The Whiskers ([dump](https://dumps.pcsx2.net/index.php/s/wATsw9Bt6K3GAmc))
- [x] Narc ([dump](https://dumps.pcsx2.net/index.php/s/9a9ttHbL35Nw4c9))
- [x] State of Emergency 2 ([dump](https://dumps.pcsx2.net/index.php/s/sSa6WyR4FgJktkF))
- [x] Singstar ([dump](https://github.com/PCSX2/pcsx2/files/5234657/gsdx_20200916145406.gs.zip))

**Games Not Tested (but potentially have the same issue):**
- State of Emergency
- Brave: The Search for Spirit Dancer
- The Powerpuff Girls: Relish Rampage

Example of the Issue:
![image](https://user-images.githubusercontent.com/26046960/71253833-08e95f80-22f7-11ea-94d4-f6fa51be60f2.png)

**Cause:**
Caused by a screen clear where the game attempts to clear a 32-bit GS texture by setting the frame buffer width to 1 and then drawing a 64x2048 quad with flat shading in order to clear the buffer to a specific color (often a pink color).

Basically because of how GS memory works, it is possible on the GS to write to the framebuffer with FBW of 1 and then starting writing again with a larger FBW value. However since the cache does not emulate this behavior, what results is a larger line on the left hand of the screen.
![_00454_f5001_rt1_03200_C_32](https://user-images.githubusercontent.com/26046960/71254183-2bc84380-22f8-11ea-9507-e730c1c0e8e7.png)

Here is an example of the incoming vertices:
```
VERTEX COORDS (XYZ)
	v0: 0.0000, 0.0000, 0
	v1: 64.0000, 2048.0000, 0

VERTEX COLOR (RGBA)
	v0: 000, 000, 000, 000
	v1: 239, 061, 239, 061
```

Here is an example FRAME register setting for the clear:
```
FRAME
	FBP (*32):0x2e00
	FBW:1
	PSM:0x0
	FBMSK:0x0
```

Here is an example of the FRAME register setting for a latter draw:
```
FRAME
	FBP (*32):0x2e00
	FBW:10
	PSM:0xa
	FBMSK:0x0
```

Previously, Superman Returns was the only game known to have this issue.

**Comment by AlessandroVetere** [comment]
I'm positive with the FBW conversion in the texture cache to tackle this issue, given also the fact that the clear is a solid rectangle draw, thus the conversion might be extremely optimized in this case.

**Comment by seta-san** [comment]
it's possible Zone of Enders:  second runner suffers from this too
![Number 2 graphical bug in cutscene on game engine](https://user-images.githubusercontent.com/8851653/101763187-0ea9f900-3aa4-11eb-8c42-f151b09ac71a.png)

**Comment by tadanokojin** [comment]
provide a gs dump so I can confirm

**Comment by seta-san** [comment]
> provide a gs dump so I can confirm

[gsdx_20201210133535.gs.zip](https://github.com/PCSX2/pcsx2/files/5675229/gsdx_20201210133535.gs.zip)

**Comment by coornio** [comment]
Here's a more modern dump from r2427. The shadows are now in the correct place, though the issue is still present. Here's a new picture too:

![gs_20220309233833](https://user-images.githubusercontent.com/11655762/157541262-8b613c64-a139-48c8-9e97-7efc68046901.png)

[gs_20220309233833.gs.zip](https://github.com/PCSX2/pcsx2/files/8218368/gs_20220309233833.gs.zip)
