### ISSUE TITLE
Meta: Z-fighting issues

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3692]
Games that have problem with textures flickering over a model. (Due to not knowing what's on top for depth)
Avoid for making duplicate issues.

- [ ] Kingdom Hearts 2 Final Mix #3394
- [ ] Raw Danger #2980
- [ ] Okami #2008
- [ ] Megaman X #1558
- [ ] J-League Pro Soccer #551
- [ ] DBZ Tenkaichi 2 and 3 #544
- [ ] Sonic Heroes #2118

**Comment by CookiePLMonster** [comment]
NASCAR Heat 2002 is notorious for those too.

**Comment by Helium-4** [comment]
There a few instances in Gran Turismo 4, are present in Software and Hardware renderers, and don't seem affected by settings or manual gamefixes
[Apricot Hill: Shadow under bridge in last turn](https://files.catbox.moe/x3mk32.7z)
[Opera Paris yellow road marking](https://files.catbox.moe/v7bsvb.7z)
[Opera Paris  building shadow on paved road segment](https://files.catbox.moe/our2ce.7z)
[Opera Paris shadow on road crossing](https://files.catbox.moe/mcfz5w.7z)

There's also a billboard very near the start of Opera Paris which has the issue but I hesitate to include it as it does exhibit a similar but much less severe variant of the issue on real hardware.

**Comment by kozarovv** [comment]
Midnight Club 3 Dub Edition Remix - Lights on rooftops, and road that is far from car, HW mode look worse.
Persona 4 - many places like school rooftop, doors in Marukyu Striptease, main street in Inaba, almost not existing in SW mode.
F1'04 - https://github.com/PCSX2/pcsx2/issues/2323
GUN - that one is interesting because it happen only in SW mode. [link](reddit.com/r/PCSX2/comments/gphp2a/software_mode_texture_flickering/)

Is worth to mention that MC3 throw warning about using old clip flag value in few places in COP2 code. 
video samples for mc3/p4: [mc3_p4.zip](https://github.com/PCSX2/pcsx2/files/5281143/mc3_p4.zip)

**Comment by incognitoh** [comment]
Also occurs with Tony Hawk's Pro Skater 3 in hardware modes. Does not seem to occur in sw mode though. Here is a quick video example of the game in hw mode (PCSX2 1.7):

[Zfighting.zip](https://github.com/PCSX2/pcsx2/files/5313970/Zfighting.zip)

**Comment by Fabianpaw** [comment]
Need For Speed - Most Wanted also has this issue on Hardware Modes when camera moves into the main menu after the memory card screen.
<details>
<summary>Gif</summary>

![flickering-mw05](https://user-images.githubusercontent.com/62476228/97029116-404f1b00-155d-11eb-8bc9-8c36a7c03106.gif)

</details>

[GSDump](https://drive.google.com/file/d/1j59-SbywrepC8u580hmiMv4NARdVzIBH/view?usp=sharing)

**Comment by ribolovac510** [comment]
In Guitar Hero on hardware renderers it is noticeable on distant geometry (especially on guitars, drums and to a lesser degree on world geometry) and also on the score counter.

![ghgeometry](https://user-images.githubusercontent.com/74596991/99536531-cdde2900-29aa-11eb-859f-76bfaf66f80c.gif)
![ghscore](https://user-images.githubusercontent.com/74596991/99536601-dfbfcc00-29aa-11eb-9909-d48b29272c80.gif)

[GH_GSDump.zip](https://github.com/PCSX2/pcsx2/files/5560326/GH_GSDump.zip)

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/139597021-e646745a-73f3-4259-9ecb-acf31d49f3c9.png)
Kuon (yang phase, happens in SW and HW), Flickering foot.

**Comment by RedDevilus** [comment]
Aggressive Inline Skating (Demo from PSmagazine24 so probably affects full game)

![image](https://user-images.githubusercontent.com/24227051/139597413-6455939e-cfa8-4329-b2da-aba46ad24527.png)

Where I marked with blue circle if you jump just before in HW mode it turns black for a second (could probably be a different issue)
Where I marked it red is one of the many z-fighting occurrences also only in HW mode.

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/139597627-c40b7aaa-c9c1-4e74-9bd0-e4fc790ac4e5.png)
Billboard and crowd seating area flickering in Toca Race Driver demo in PSmagazine24.

**Comment by iamthelaw2041** [comment]
Is this the same issue that's being described here?

![sti](https://user-images.githubusercontent.com/94656803/143297796-5af3a24a-0535-4ca2-a48c-5f0800019c34.PNG)


https://wiki.pcsx2.net/Disney%27s_Stitch:_Experiment_626

**Comment by refractionpcsx2** [comment]
Not if framebuffer conversion fixes it, no

**Comment by TransparentBlue** [comment]
Ape escape 3 has some Zfighting on a billboard in the Wild West level
It's present in both HW and SW though less intense in SW
I cannot upload the GS dump directly on Github as the smallest I've managed to capture that illustrates the issue is still too large.
[Ape Escape 3 - Wild West Zfigthing.7z](https://1.filedit.ch/1/paaVHXYpzwlQBwDVnfn.7z)

**Comment by HeroponRikiBestest** [comment]
Snoopy exhibits z-fighting as described in https://github.com/PCSX2/pcsx2/issues/5240

**Comment by AhayriSG** [comment]
Harry Potter and The Chamber of Secrets (SLUS-20576)
GSDump: https://www.mediafire.com/file/t1tj6id3vmo77l4/SLUS-20576.7z/file

**Comment by coornio** [comment]
Potentially Rayman 3 as well in #6101

**Comment by no008080** [comment]
Shadow of the Colossus does it in every hardware mode at any resolution. Observable when looking at a structure or a landscape at a distance.
![Shadow of the Colossus_SCES-53326_20220801010713_(3)](https://user-images.githubusercontent.com/97309764/182049084-ab35254c-8aef-4994-b8ee-1fce7defa6cb.png)
![Shadow of the Colossus_SCES-53326_20220801010714](https://user-images.githubusercontent.com/97309764/182049087-780dc460-9755-4958-bdf5-dbe5cc01c7bd.png)

**Comment by Zombeaver** [comment]
Beat Down: Fists of Vengeance has quite a bit of z-fighting on a number of distant objects, including character models.

https://i.imgur.com/kywJiNo.gif

**Comment by Zombeaver** [comment]
Legend of Kay has significant z-fighting even on nearby objects.

https://i.imgur.com/wZTFmCV.gif

**Comment by Zombeaver** [comment]
Certain areas in Castlevania: Lament of Innocence have z-fighting.

https://i.imgur.com/r3D7TYU.gif

**Comment by Jakey757** [comment]
Theater stage in Silent hill Origins in SW+HW

https://user-images.githubusercontent.com/49990481/200138642-a038647d-d38f-4728-896f-85c92298441e.mp4


https://user-images.githubusercontent.com/49990481/200138643-afbe5457-d9db-4d02-8018-e5ad01e38fc6.mp4

**Comment by Smerg-the-Dargon** [comment]
Shin Megami Tensei: Digital Devil Saga 1 and 2 both have what I'm pretty sure are z-fighting issues - various shadows begin to flicker, although whether it occurs seems to depend on where you're standing relative to the shadows.
Only happens in HW mode, tested with all renderers. It's visible in the very first room of DDS2.

![pcsx2-qtx64-avx2_STF1dgNb32](https://user-images.githubusercontent.com/40700180/201404659-6b736a9c-252c-48d2-86be-ce42ae86ec5b.png)
![pcsx2-qtx64-avx2_bBXUV0W46h](https://user-images.githubusercontent.com/40700180/201404662-c01170ea-54e7-4f85-a86c-9dc143744234.png)

**Comment by washingleavesandthensome23-434** [comment]
Hope this gets fixed soon, appreciated

**Comment by bigol83** [comment]
Since my issue is a duplicate would you please add link to the meta description? Now, it's just simple text, while my #8858 report is much more complete.

**Comment by washingleavesandthensome23-434** [comment]
Hope this issue will be resolved soon , Onimusha 3 got some crazy z fighting but dmc1 and others as well

**Comment by PoloniumRain** [comment]
@refractionpcsx2 So from your last comment in #3811 will you essentially need 64-bit precision on GPU's before this can be fixed? That would be a shame because this the biggest problem i've come across in quite a few games.

One obvious example:

https://github.com/PCSX2/pcsx2/assets/50634894/6b8a2eb9-779d-4c7d-afe1-72260536ad91

**Comment by stenzek** [comment]
Yes, or we can use integer depth via rov. Neither is fast.

**Comment by dante3732** [comment]
Maybe it same in Shadow Tower Abyss.
https://drive.google.com/file/d/1n-stIH-NgFGCwP92kQD0JI0Oghyxqxna/view?usp=sharing

**Comment by dante3732** [comment]
Seems Onimusha 3 also have ths issue. 

https://github.com/PCSX2/pcsx2/assets/66036249/9bb1470b-31bf-4408-8ea8-73a4bcd3692c

**Comment by woj1993** [comment]
Will using "integer depth via rov" will really be so slow that we won't be able to emulate games at decent speed? I mean some time has passed from when this project was started and computers got faster.

**Comment by dante3732** [comment]
ROV will not work on NVIDIA older than 1xxx cards, and on AMD it may not work at all.

**Comment by JordanTheToaster** [comment]
> ROV will not work on NVIDIA older than 1xxx cards, and on AMD it may not work at all.

ROV works on RDNA 2 and up perfectly fine but let's not crowd up these comments please.

**Comment by TheTechnician27** [comment]
Red, can you add Sonic Unleashed? I tested it a while ago and saw z-fighting issues, and testing it again today, they're definitely there. For example, if you go to the shrine and look at the Sun door, it starts z-fighting.

**Comment by TheTechnician27** [comment]
Z-fighting is also prevalent in Powerpuff Girls: Relish Rampage. There's very visible z-fighting on buildings and on the windows of vehicles.

**Comment by dante3732** [comment]
Probably Vampire Night also have this issue.

**Comment by bigol83** [comment]
Suikoden V and Dark Chronicle have it too, 

Suikoden V is visible on dock columns in Sol Falena and during the Lelcar town attack
https://youtu.be/rwLb7IpMOWA?t=637
Dark Chronicle has it on train windows when you go towards it on Forest dungeon 
[Dark Chronicle_SCES-51190_20240115133513_2.zip](https://github.com/PCSX2/pcsx2/files/13938927/Dark.Chronicle_SCES-51190_20240115133513_2.zip)

**Comment by xzn** [comment]
I've come up with two fixes (or hacks) for two different games that I've tested, not sure how well they generalize to other games:

**For Quake III Revolution:**

The depth values are very large but the actual range used doesn't seem to be more than 24-bit, so we can chop the top 8 MSBs from the depth values in the vertex shader and more or less fix the shadows.

![image](https://github.com/PCSX2/pcsx2/assets/1617680/5307e513-69e4-470d-9e38-8274968831bf)

![image](https://github.com/PCSX2/pcsx2/assets/1617680/d3de2524-decb-443c-aff1-648daf6d79f6)

This has almost no performance cost and can be done in all HW renderers.

**For GTA III LCS:**

The depth test are greater or equal, and the floating point fraction is too accurate, chopping the interpolated depth to integer fixes the decals for the most part.

![image](https://github.com/PCSX2/pcsx2/assets/1617680/399f2cfa-2ffa-4a69-aa67-597fcf3bc34f)

![image](https://github.com/PCSX2/pcsx2/assets/1617680/28078142-e8b0-40e4-bed7-87c54d71fe03)

This requires assigning to gl_FragDepth (for OpenGL and Vulkan) or whatever is equivalent in D3D11 and D3D12. The performance drop is around 33% to 40% in GPU since there's no longer early z test. (Conservative depth may help but from my test it doesn't seem to do much)

**Example shader:**

(For Vulkan: `resources\shaders\vulkan`)
[tfx.glsl.zip](https://github.com/PCSX2/pcsx2/files/14454636/tfx.glsl.zip)



**Some side notes:**

While ROV allows 32-bit integer to be used for depth, there's also the problem of interpolating 32-bit depth values between vertexes on the GPU. No idea how to do that..

The simple way of using two floats and stitching the result together:

```glsl
// vertex shader
vsOut.z_hi = float(z / (1 << 24));
vsOut.z_lo = float(z % (1 << 24));

// fragment shader
uint z = uint(roundEven(vsIn.z_lo)) + uint(vsIn.z_hi * float(1 << 24));
```

Pretty sure there's still fractional error when done this way. And lacking real games to test the result would be just placebo.

Let's say we solve the problem of 32-bit interpolation however, we could abuse the representation of float and cram ~29 bits of information between 0.0f and 1.0f (using `uintBitsToFloat`), With `VK_EXT_depth_range_unrestricted` on Vulkan we have ~30 bits to work with. (between 0.0f and FLT_MAX from my test is possible: abs(minDepth - maxDepth) can't be more than FLT_MAX it seemed). May not matter but it's better than the 24-bit we have currently.

**Comment by refractionpcsx2** [comment]
the problem with late depth tests is because we do software blending in the shader, a late z test is too late, then the pixel is wrong, even though the Z is now right.

It's a serious chicken + egg problem which we've run in to before :(

but yeah being able to extend the range of the depth is the only real way to fix it, since we only have 23 bits of precision now, 30 would be a huge improvement.

**Comment by xzn** [comment]
The 30-bit I mentioned is only for storage in depth buffer unfortunately (where only greater or equal matters, not the actual values for perspective). For early z-test and perspective there's only the regular floats apparently.

ROV would have the same restriction it seems.

**Comment by stenzek** [comment]
Tellow has proposed an alternative approach previously; (if I remember correctly) take the minimum Z of the primitive, subtract it from the Z which is interpolated, and then re-add it before writing `SV_Depth`. This would also solve the interpolation precision problem, but would also require splitting the batch if the Z range across triangles is too large.

It's not something I've addressed in the current iteration of the ROV PR, but yes, long-term we'll probably have to support full integer depth. Note that even software isn't 100% precise in this manner; it uses doubles for interpolating, I'm not sure how the PS2 hardware itself interpolates.

As for hacks, another option is to just scale the depth down to a more restricted range. Sorta like what we do when clip control isn't supported, but instead of clamping to 2^24-1, scale it instead.

**Comment by anffss** [comment]
[xzn](https://github.com/xzn), thank you for the shader tfx.glsl! Now the Z-fighting in Pro Evolution Soccer 2008 almost defeated, but still a little bit remains on the hair and some parts of kit model. What should I change in this shader file to finally fix the flickering? Are there any values that can be changed and checked result in the game?

**Comment by xzn** [comment]
@anffss 

I took a look at your bug report linked in the OP and could not reproduce it with the latest pcsx2 even without the shader change. Perhaps there have been changes in pcsx2 in the last two years that fixed the bug on the cloth already?

For the hair and whatever you mean by kit model, are you placing the shader in the directory indicated and using the Vulkan renderer? (The shader is for Vulkan only)

**Comment by xzn** [comment]
Correct me if I'm wrong: the VUs on PS2 used for vertex transform has 24-bit precision as well since they use floats. So how do 32-bits depth even come about? When the VUs convert floating vertexes to integer for the GS, assuming they don't do too many weird post-processing, we don't actually have to worry about splitting triangles into batches, because all the primitive in the same scene would fall into the same 24-bit range.

I don't know if any game does this but it's possible to have different depth base offset in order to render different 3D scenes on top of each other. Otherwise the shader change above would work generally for most games I think.

This also means that we can most likely get away with no rov since it's unlikely a game will have all 8 bits of remaining depth precision to have hundreds of 3D scenes at once.

(Also I realized that late depth isn't needed for the GTA III LCS case above: assuming that the game doesn't use the full 24-bit depth precision, which seems to be the case for some reason, just set the 24th bit always in vertex shader, then the interpolated floating point will have precision exactly to the equivalent integer part without fractional part: [tfx.glsl.zip](https://github.com/PCSX2/pcsx2/files/14534313/tfx.glsl.zip) )

There's still some artifact but it can't be helped for now: (ideally this shouldn't have the strips across the decal)
![gta3lcs](https://github.com/PCSX2/pcsx2/assets/1617680/ef2b4dea-967b-4f98-81fb-b86d2217afb4)

**Comment by anffss** [comment]
xzn, of course I'm using one of the latest versions of pcsx2 and vulkan renderer. Shader file copied is in the correct folder (resources/shaders/vulkan). I've tried both the one you posted above and the one a few posts earlier. However, z fighting persists. That's why I asked if there might be any other options to improve the depth accuracy.

![image](https://github.com/PCSX2/pcsx2/assets/117391433/9bb62fa0-034c-4636-b8f3-dc8702b0d042)
![image](https://github.com/PCSX2/pcsx2/assets/117391433/feb9eb69-4e4d-44ca-94db-c54219267c36)
![image](https://github.com/PCSX2/pcsx2/assets/117391433/7599b374-be95-4670-b042-ed0637c61354)

**Comment by bigol83** [comment]
The hair fighting only happens on hardware, not software renderer. Later i will check a dump i took that clearly shows the issue on Ps2 to see if the native resolution hides the fighting, but i think that won't be the case considering that Pcsx2 software renderer already doesn't have this hair z fighting issue.

**Comment by dante3732** [comment]
Seems same in Van Helsing.
![pcsx2-qt_2024_03_21_22_54_53_655](https://github.com/PCSX2/pcsx2/assets/66036249/8b90d10c-0b58-43f8-b85a-ca128ba468e3)
![pcsx2-qt_2024_03_21_22_55_00_928](https://github.com/PCSX2/pcsx2/assets/66036249/c7716353-f2ef-4d4a-9ea3-b9176bf91a05)

**Comment by superblobster** [comment]
Rule of Rose is another affected game:

https://github.com/PCSX2/pcsx2/assets/60817163/7a98478f-9581-4a4f-833c-cb218a2ed770

**Comment by RicardsRikmanis** [comment]
@xzn I've tried your shader on King's Field: The Ancient City and it's a definite improvement. I still see some z-fighting rarely but it's also present in software mode.

**Comment by refractionpcsx2** [comment]
Castlevania Curse of Darkness as well, as reported here: #11436

**Comment by jcolell** [comment]
I have the same problem in Buffy the Vampire Slayer: Chaos Bleeds. I remember that in past versions there wasn't this problem

https://github.com/PCSX2/pcsx2/assets/80860708/9ffe7c47-214b-467f-a2c4-8c291214fbaa

**Comment by joepogo** [comment]
I opened up a bug report that got closed yesterday but I think I should have just chimed in here instead now that I'm more familiar with pcsc2 issues. 

There now appears to be z-fighting issues in tony hawks underground (THUG) I'm using the newest nightly version and there's also no loading screens now for this game.

**Comment by anffss** [comment]
@xzn 
Your shader file did reduce the flickering a bit. But it doesn't work in the new version of pcsx2, could you please update it?

**Comment by Sol1vaN** [comment]
and quake 3 still have the z-fighting a lot, is very sad that still persit until now 😥
is true that in software render the z fight dissapear, but the native resolution is too low.

**Comment by KiriSweets** [comment]
Castlevania Lament of Innocence also has the issue in Hardware. Software rarely has it and when it does it's much less pronounced (resolution is irrelevant to it happening also). Screenshot brightened for visibility and compares the shadow on the sconce.

![Image](https://github.com/user-attachments/assets/146775aa-62c7-4f58-b644-d601d230e220)

**Comment by refractionpcsx2** [comment]
Software mode on PCSX2 has also had the problem solved for ages, since Parallel-GS is basically a fancy software renderer. It's not so easy to fix on a hardware renderer due to how depth works on GPU's.

**Comment by ezdahmad** [comment]
> Software mode on PCSX2 has also had the problem solved for ages, since Parallel-GS is basically a fancy software renderer. It's not so easy to fix on a hardware renderer due to how depth works on GPU's.

but in the case of PES (Pro Evolution Soccer) games using PCXS2, the flickering is improved when using software renderer, but not completely fixed. I just checked again. I'll try to make screenshots for comparison and illustration.

**Comment by refractionpcsx2** [comment]
if it's not fixed in SW mode, it's either something else or it has the flickering in real hardware too, it should be plenty accurate enough on that front (and there have been cases of people claiming z fighting which was there on real hardware)

**Comment by ezdahmad** [comment]
> if it's not fixed in SW mode, it's either something else or it has the flickering in real hardware too, it should be plenty accurate enough on that front (and there have been cases of people claiming z fighting which was there on real hardware)

Aha I see, actually you might be right, I'll do a thorough testing and comparison sometime next week with all the assigned settings and post screenshots,

I was checking using the real hardware on a real sony pvm crt, and I did notice the flicker (it was not obvious, but it is there indeed), strange enough using "Parallel-GS" it was better than the real hardware (in terms of the flickering), no flickering at all. 

Again, once my tests are fully concluded I'm gonna post it here, hopefully it can benefit you guys in some ways.

**Comment by dante3732** [comment]
> Vulkan based paraLLEl-GS renderer

Only for native resolution?

**Comment by ezdahmad** [comment]
> > Vulkan based paraLLEl-GS renderer
> 
> Only for native resolution?

![Image](https://github.com/user-attachments/assets/0886cb2b-29f3-470f-a85b-c2bd5414ff4a)

**Comment by PoloniumRain** [comment]
> Only for native resolution?

You can upscale _many_ games with the `ParaLLEl experimental High-res scanout` feature, but some games requiem patches. 

Quake III can't be upscaled, but most of the games i've tried so far are working with it.

When it upscales it looks like 1080p and you can't change this. So 4K just wont work. But you can use up to 16x SSAA, so even at 1080p-ish resolution, most games still look pretty great. This is probably why @ezdahmad is seeing less flicker than on real hardware.

> since Parallel-GS is basically a fancy software renderer.

That's interesting. Because paraLLEl-GS acts, looks and performs like a hardware renderer. So i suppose it doesn't really matter if it's a hardware renderer or not when the end result is this good.

**Comment by dante3732** [comment]
> You can upscale _many_ games with the `ParaLLEl experimental High-res scanout` feature, but some games require patches.

4x resolution much better than 16 SSAA on paraLLEl-GS.😒

native paraLLEl-GS
![Image](https://github.com/user-attachments/assets/668718ea-2b64-4392-865f-370c050934e0)

16x SSAA
![Image](https://github.com/user-attachments/assets/3b41f60e-b56c-42fd-823f-375a592b2145)

4x d3d12 
![Image](https://github.com/user-attachments/assets/52dc1305-21d0-4cd3-8ee5-12d7db6479bb)

**Comment by PoloniumRain** [comment]
> 4x resolution much better than 16 SSAA on paraLLEl-GS.😒

Well yeah, because 4x native res is around 1440p for many PS2 games, and i said it's looks like 1080p with paraLLEl.

But for some games like Tekken 5, 16x SSAA + `paraLLEl experimental High-res scanout` will look similar to PCSX2 with 4x res scaling. It entirely depends on the game. But most look 1080p.

Enabling 16x SSAA + `paraLLE experimental SSAA texture` will also increase the res in _some_ games. Shadow of the Colossus is one example where it will produce an image similar to 900p, while some games will look as good as 1440p, and others don't look any different.

`paraLLE experimental sharp backbuffer` can also make some games look higher res/sharper.

Many game needs different settings and will have different results.

**Comment by dante3732** [comment]
> Well yeah, because 4x native res is around 1440p for many PS2 games, and i said it's looks like 1080p with paraLLEl.

No, even 2x native looks better, than 16 SSAA. SSAA in this case simply smooths out the pixels.

![Image](https://github.com/user-attachments/assets/86117aed-0262-47c4-9ee5-4d5f1bee008b)

**Comment by Darkcranio95** [comment]
Can attest that even for Budokai Tenkaichi 2 and 3 paraLLEl-GS solves Z fighting issues compiled to PCSX2 as a renderer.
PCSX2 software renderer makes it better but does not solve it. And no, real hardware does not have it.....
It doesn't look 1080p with HD scanout. More "around" 720p 2x.

**Comment by ghost** [comment]
Adding Rayman 2. 

![Image](https://github.com/user-attachments/assets/b354cb01-a176-477d-a070-74aad4513657)

 His hoodie and the river are both affected. [Rayman 2 - Revolution_SLUS-20138_20250605170108.gs.zip](https://github.com/user-attachments/files/20612396/Rayman.2.-.Revolution_SLUS-20138_20250605170108.gs.zip)

**Comment by ghost** [comment]
Adding Jackie Chan Adventures.

The chair turns black sometimes

![Image](https://github.com/user-attachments/assets/dbdba51e-7b75-42a9-b74e-8226e6f4e9a5)

![Image](https://github.com/user-attachments/assets/0dc415c0-3946-4ad5-82e0-0a57455ef244)

Dump:
[Jackie Chan Adventures_SCES-52412_20250607130430.gs.zip](https://github.com/user-attachments/files/20638156/Jackie.Chan.Adventures_SCES-52412_20250607130430.gs.zip)

**Comment by bigol83** [comment]
Max Payne during tutorial you can see the ad flickering in the distance

https://github.com/user-attachments/assets/531482f9-1103-4107-82c9-21980c0b4309

https://files.catbox.moe/j3c5m8.xz

**Comment by SMGgoPrrrrrr** [comment]
The scooby doo 100 frights game has flickering textures not present on software mode how did dolphin emulator got that fixed?

**Comment by RedPanda4552** [comment]
> The scooby doo 100 frights game has flickering textures not present on software mode how did dolphin emulator got that fixed?

Dolphin isn't a PS2 emulator.

**Comment by hroedrich-alt** [comment]
so

> > The scooby doo 100 frights game has flickering textures not present on software mode how did dolphin emulator got that fixed?
> 
> Dolphin isn't a PS2 emulator.

but can you fix like they did?

**Comment by Triticum0** [comment]
What of what is left on list need retesting?

**Comment by refractionpcsx2** [comment]
Anything that isn't ticked

**Comment by mrrguest** [comment]
I tried Fatal Frame 3 and z-fighting is fixed too
https://github.com/PCSX2/pcsx2/pull/13795#issuecomment-3730293290

**Comment by PassionWagon** [comment]
Issue happens with Dynasty Warriors 2 and 3 as well.
