### ISSUE TITLE
Meta: Games that need switch to SW for FMV Gamefix.

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3805]
The current gamefix is a hack and not a proper solution.

Games affected:

- [ ] God of War
- [ ] Silent Hill 2
- [ ] Kingdom Hearts Re: Chain of Memories
- [ ] Silent Hill 3
- [ ] Twisted Black Metal

**Comment by yxmline** [comment]
Gradius V [NTSC-J]
`The second level cutscenes FMV animation flower screen`
Grandia III [NTSC-J]
`FMV animation top flickering and flower screen`
Sakura - Yuki Gekka [NTSC-J]
`FMV animation flicker`
Final Fantasy X-2 - International + Last Mission [NTSC-J]
`The bottom of the animation flickers and the screen is dark`
Red Ninja - End of Honor [NTSC-J]
`FMV animation flicker`
Summon Night Gran-These: Horobi no Ken to Yakusoku no Kishi [NTSC-J]
`FMV animation flicker`

**Comment by tadanokojin** [comment]
Silent Hill 2 and 3 should be sorted:
https://wiki.pcsx2.net/Silent_Hill_2
https://wiki.pcsx2.net/Silent_Hill_3

I'm guessing since the gamefix in the gamedb mentions these two they originally had the gamefix automatically applied but they were removed when they were fixed proper.

KH3, again same deal it's been fixed without the hack:
https://wiki.pcsx2.net/Kingdom_Hearts_Re:_Chain_of_Memories

Twisted metal black I don't see any mention of FMV issues on the wiki but I tested it and it's fine as far as I can tell.

Rule of Rose should be fixed:
https://wiki.pcsx2.net/Rule_of_Rose

I didn't test it but ape escape 2 and 3 should be worked around automatically now via safe features:
https://wiki.pcsx2.net/Ape_Escape_3
https://wiki.pcsx2.net/Ape_Escape_2

**Comment by kozarovv** [comment]
According to wiki: Grandia Xtreme - Enable manual gamefix to switch GSdx to software rendering during FMVs to get rid of flickering video. 

But report is from 1.1.0, so that can be fixed already.

**Comment by DonelBueno** [comment]
Ridge Racer V: HW renderer can't render the opening FMV.

Partially https://github.com/PCSX2/pcsx2/issues/3278

**Comment by tadanokojin** [comment]
@DonelBueno that's in-engine not an FMV

**Comment by DonelBueno** [comment]
@tadanokojin oh, sorry, I didn't know that.

That makes the issue even more strange.

**Comment by abogard** [comment]
It says here that Silent Hill 3 is fixed, but strangely enough for me it's always necessary to switch to software, these days though I have to use F9 because "switch to SW for FMV" is broken.

**Comment by refractionpcsx2** [comment]
> It says here that Silent Hill 3 is fixed, but strangely enough for me it's always necessary to switch to software, these days though I have to use F9 because "switch to SW for FMV" is broken.

how is it broken? It looks fine here (I marked it as fixed)

**Comment by abogard** [comment]
> > It says here that Silent Hill 3 is fixed, but strangely enough for me it's always necessary to switch to software, these days though I have to use F9 because "switch to SW for FMV" is broken.
> 
> how is it broken? It looks fine here (I marked it as fixed)
> ![silenthill3vid](https://user-images.githubusercontent.com/6278726/95658891-95c70900-0b15-11eb-9c8f-204330d59f56.png)

I see. Still, I don't know why it happens to me. If I use hardware renderer the movies play but I only see a black screen, it's the usual traditional problem. I fix it by pressing F9, in fact I just downloaded the last version of the emulator and tried again, the problem persists. I'm using the NTSC version of the game though (SLUS-20622), I don't know if that has anything to do with it.

**Comment by refractionpcsx2** [comment]
Are you possibly using a really old version of GSDX like the AVX version (not AVX2) or SSSE3? because they were discontinued a long time ago and may be missing fixes.

**Comment by abogard** [comment]
I use AVX2 with OGL. As far as I can see the only difference is the version of the game. It would be useful if someone else could test the NTSC version.

**Comment by refractionpcsx2** [comment]
> I use AVX2 with OGL. As far as I can see the only difference is the version of the game. It would be useful if someone else could test the NTSC version.

That does seem to be the case, I've updated the OP to reflect that the NTSC version sucks :P

**Comment by abogard** [comment]
Ok, I did my research. A friend of mine has the PAL version of the game (SLES-51434), so I just went over to his house, we did the testing and I can confirm the PAL version to be working; but if you choose NTSC 60 Hz (as opposed to PAL 50 Hz) in the video format selection screen at the beginning of the game you can reproduce the problem even in the PAL version.

**Comment by refractionpcsx2** [comment]
Very strange. I don't get the Hz selector on my version so I cannot confirm that personally, but it's likely to be the same issue as NTSC, so that's fine.

**Comment by abogard** [comment]
![image](https://user-images.githubusercontent.com/59800992/95661365-ed507f00-0aeb-11eb-8f48-d7cac28c8f8a.png)

**Comment by refractionpcsx2** [comment]
Yeah I don't get that

**Comment by lightningterror** [comment]
https://github.com/PCSX2/pcsx2/issues/112

**Comment by scju** [comment]
> Gradius V [NTSC-J]
> `FMV animation flower screen`
> Grandia III [NTSC-J]
> `FMV animation flickering and flower screen`
> Sakura - Yuki Gekka [NTSC-J]
> `FMV animation flicker`
> Final Fantasy X-2 - International + Last Mission [NTSC-J]
> `FMV animation flickers and the screen is dark`
> Red Ninja - End of Honor [NTSC-J]
> `FMV animation flicker`
> Summon Night Gran-These: Horobi no Ken to Yakusoku no Kishi [NTSC-J]
> `FMV animation flicker`

Dynasty Warriors 3 [NTSC-C] [NTSC-U]
`FMV animation flicker`

**Comment by tadanokojin** [comment]
Dynasty Warriors looks like an upscaling problem. The FMVs seem fine on native.

**Comment by tadanokojin** [comment]
Before anything is mentioned in the thread the following should be tried:
- enabling large framebuffer (this usually resolve flicker)
- enabling memory wrapping

If neither of those work you may post here. I want to avoid polluting the thread with stuff that already has workarounds. If you happen to notice these fixing anything feel free to update the wiki or submit a compatibility report.

**Comment by trostboot** [comment]
Grandia Xtreme (SLUS-20417) exhibits the following FMV issues (all OGL HW):

- Heavy flickering on initial boot at native resolution - will resolve if renderer is restarted, for example by opening the gsdx config menu or pausing and resuming. Memory wrapping has no effect.
- Heavy flickering + additional visual glitches at non-native resolutions. Glitches can be fixed with large framebuffer, flickering requires renderer restart.

**Comment by FuxorLuck** [comment]
please add "Dual Hearts" to this list
![pcsx2 2020-11-29 15-25-28](https://user-images.githubusercontent.com/55870574/100543165-394fb280-3257-11eb-951c-869a9c68b9d2.png)
![pcsx2 2020-11-29 15-25-43](https://user-images.githubusercontent.com/55870574/100543168-3bb20c80-3257-11eb-8589-08601364d45e.png)

**Comment by MilesTeg81** [comment]
Baldurs Gate: DA NTSC, D3D 11 HW, 1.6 & 1.7 nightly build

Testsys:
Ryzen 5 3600
Radeon 5500X

Heavy flickering on all vids  

screenhot shows flicker while WizardoftheCoast-Logo is playing:
![bgda-flicker-wotc-logovid](https://user-images.githubusercontent.com/6051886/101790231-8575df00-3b02-11eb-9765-9281a41cc5e0.png)

large framebuffer / memory wrapping have no effect on this.

Switch to SW for FMV Gamefix from 1.6.0 solves this.

**Comment by Medard22** [comment]
Drakengard - there is a bar of distorted video on the right side. Latest 1.7.0 dev build 170d1cb. Fixed in SW mode.

![gsdx_20210108203213](https://user-images.githubusercontent.com/42897361/104056623-179c0080-51f1-11eb-9432-30b166de8691.png)

**Comment by abusuzuki** [comment]
"Gundam lost war chronicle" still shows flickering on FMV even when enabling  large framebuffer  &  memory wrapping , tested on 1.7.0 dev build

**Comment by garouvulps** [comment]
Berserk: Millennium Falcon Hen Seima Senki no Shou 
FMV cutscenes do not show subtitles in both Directx11 and OpenGL hardware mode, only in software mode
tested on v1.7.0-dev-1198-g6f7890b70 build 
tested with native and 2x(720p) resolutions, with and without large framebuffer (disable conservative box) and memory wrapping enabled

**Comment by felixthecat1970** [comment]
workaround for Silent Hill 3 (USA) (En,Ja,Fr,De,Es,It,Ko) SLUS_206.22;1 Game CRC = 0x2498951B videos in HW mode https://forums.pcsx2.net/Thread-Fixing-unplayable-games?pid=619120#pid619120

**Comment by refractionpcsx2** [comment]
There's a japanese game called Grappler Baki which only displays the FMV in the top left corner in hardware mode

![image](https://user-images.githubusercontent.com/6278726/125204894-55004a00-e277-11eb-9a97-9ae9220519b8.png)

**Comment by BigheadSMZ** [comment]
I recently discovered that the SW hack for FMVs was removed. I just wanted to point out that "Castlevania: Curse of Darkness" also has FMV issues which were solved by this hack, so there is currently no way to fix them when using hardware. The wiki mentions to enable this which lead me down a rabbit hole and ended up here.

https://wiki.pcsx2.net/index.php?title=Castlevania:_Curse_of_Darkness

**Comment by refractionpcsx2** [comment]
@BigheadSMZ you will need to press F9 when the FMV plays to switch manually, but hopefully it can be fixed in the future

**Comment by ynazar1** [comment]
> @BigheadSMZ you will need to press F9 when the FMV plays to switch manually, but hopefully it can be fixed in the future

@refractionpcsx2 I'm really hoping it will get fixed in the near future. Ie: Having to press f9 all the time for games with a lot of little cutscenes, especially in the beginning, ie FFX-2; really breaks the immersion, especially when playing with a controller and keyboard is reasonably far away.

**Comment by TheTechnician27** [comment]
Bolt [NTSC-U]: Extreme flickering in cutscenes when using HW renderer. See: https://www.youtube.com/watch?v=HCJ7N3_7AcQ

**Comment by Tzerinas** [comment]
> Grandia Xtreme (SLUS-20417) exhibits the following FMV issues (all OGL HW):
> 
> * Heavy flickering on initial boot at native resolution - will resolve if renderer is restarted, for example by opening the gsdx config menu or pausing and resuming. Memory wrapping has no effect.
> * Heavy flickering + additional visual glitches at non-native resolutions. Glitches can be fixed with large framebuffer, flickering requires renderer restart.

Can confirm that these issues still exist as of latest master. Really bad flickers too (I had a headache looking at it).

**Comment by seta-san** [comment]
i think masters of the universe - defenders of greyskull needs to be added "SLES-53035" fmv has flashing problem in hardware. it is a PAL game.

**Comment by seta-san** [comment]
Come to think of it. Would it cause any issues to just make this default behavior. Are there any fmv that do worse on software mode than hardware?

**Comment by RedDevilus** [comment]
Not really but hiding the issue is not a good idea for a better solution in the future.

**Comment by refractionpcsx2** [comment]
That's why this thread is here, to track what games need the switch so maybe one day they can be fixed properly in the HW renderer. But for now if a game needs it, it needs adding to the GameDB.

**Comment by Tzerinas** [comment]
Tak and the Power of Juju as well as Tak 2 both experience heavy flicker.

**Comment by Tzerinas** [comment]
The ICO FMV opening also needs the Hack. Only displays the top left corner in Hardware.

![gs_20220321172900_Ico _NTSC-U__SCUS-97113](https://user-images.githubusercontent.com/98034944/159344160-866b5b5d-ab6e-4af5-8728-23aef5e9f4e5.png)

**Comment by refractionpcsx2** [comment]
I should point out by "opening FMV" Tzerinas means not the first one, but if you wait at the main menu, the video it plays after that is broken in hw.

**Comment by ynazar1** [comment]
With the Qt UI the SW FMV renderer checkbox seems to be back. I'm not sure if that's intentional or not. 
I'll also add that `Final Fantasy X-2 SLUS-20672` does not seem to have FMV problems even with HW rendering enabled as default anymore in my limited testing.

**Comment by refractionpcsx2** [comment]
It's been back for like a year in wx

**Comment by ichee** [comment]
> please add "Dual Hearts" to this list ![pcsx2 2020-11-29 15-25-28](https://user-images.githubusercontent.com/55870574/100543165-394fb280-3257-11eb-951c-869a9c68b9d2.png) ![pcsx2 2020-11-29 15-25-43](https://user-images.githubusercontent.com/55870574/100543168-3bb20c80-3257-11eb-8589-08601364d45e.png)

Enabling `Texture Inside RT` fixes the FMV flicker and graphic retention glitches for the remainder of the current play session, though they will return when restarting the game until the setting is toggled again.
