### ISSUE TITLE
USB: Issues with Wheel device support

### ISSUE THREAD

**Issue by CookiePLMonster** [PCSX2/pcsx2#3926]
Upon attempting to use USB steering wheel emulation with **PCSX2 v1.7.0-dev-593-g35122e660** and **DInput device API** I quickly encountered an array of issues. This issue serves as a tracker for all those.

I currently have not gathered any logs. I assume that for more information I need to provide logs generated by enabling the logging option from **USB Settings**.

## FFB issues:
- [x] **Force Feedback randomly doesn't initialize** - this seems to be inconsistent, but launching PCSX2 can result in Force Feedback not working (not in game nor in the Test screen). No particular pattern (e.g. every second launch) seems to exist. This might very well be an issue of wheel's drivers, but in this case I assume DirectInput should report the failure somewhere down the line. **Fixed with #4042**
- [x] **Force Feedback strength seems to malfunction** - in cases where the above point doesn't apply (i.e. FFB initialized correctly), Force Feedback appears to be so strong it could be a hazard. Turning down the **Gain** option does not actually seem to decrease the force of effects. **Fixed with #4042**
- [x] **Pausing emulation does not disable Force Feedback effects** - effects playing at the time of pausing emulations don't stop, which, combined with the previous point, can result in a rather unpleasant (if not dangerous) experience. **Fixed with #4042**

## UI issues:
- [ ] **UI remains unresponsive during the Force Feedback test** - a minor UI issue, but in cases where Test doesn't play any FFB effects (e.g. like when it doesn't initialize) it can be rather confusing.

## Wheel emulation issues (maybe? Need confirmation):
- ~**GT Force wheel malfunctions with NASCAR Heat 2002** - all proof of the GT Force working with this game Is an article [HERE](https://www.gamezone.com/news/nascar_heat_2002_to_support_logitech_force_feedback_wheel/), but attempting to do so in PCSX2 results in a rather broken experience - the game lacks any in-game remapping for the steering wheel (so I assume it should have been properly bound out of the box), but pedals don't work as expected. Instead, Circle/Cross function as throttle/brake.~ **Invalid - it's a game bug. Restoring controller mappings to Default "fixes" it.**

All those issues were encountered with a Thrustmaster T300RS GT and a DInput API enabled in the USB settings.

**Comment by Fabianpaw** [comment]
Just wanted to add that these issues are not just specific to Thrustmaster wheels, as quite a few of them happen with my Logitech G29 using PS3 Mode aswell, though less often and less severe in my testing.
Also worth adding that the "TEST" button in the DInput Config is broken by the 2nd issue @CookiePLMonster mentioned, as it's always turning the wheel at max speed.

**Comment by jackun** [comment]
> Force Feedback strength 

Best to set it from wheel's control panel etc. Too many differently powered wheels.

> always turning the wheel at max speed

Currently probably too strong but some "wheels" are so ass they don't even properly turn  with supposed half-strength probably

**Comment by CookiePLMonster** [comment]
> Best to set it from wheel's control panel etc. Too many differently powered wheels.

I don't agree. This is not about the FFB strength itself (which is fine in other games), but more about the fact that the Gain option seems not to work correctly. If PCSX2 is the only application to give me dangerously strong FFB and I am unable to successfully change it from its options, I shouldn't have to change it from the control panel.

**Comment by Fabianpaw** [comment]
Especially when many wheels, such like my G29, don't even have any control panel allowing you to change FFB strength.
Almost all PC/Console Racing Games meant to be played with wheel have FFB Options to make up for this, PCSX2 doesn't.

**Comment by jackun** [comment]
Not even G HUB? Weird, gain is set. Have to check why it's ignored then.

**Comment by Fabianpaw** [comment]
G Hub doesn't have any relevant settings, and neither does the older Logitech Gaming Software.

**Comment by jackun** [comment]
Must be remembering it wrong then about ghub.

Can you build PCSX2 yourself to speed up testing? Sprinkle some DIEP_GAIN on every `SetParameters`

**Comment by CookiePLMonster** [comment]
The issue with GT Force malfunctioning in NASCAR Heat 2002 turned out to be a game bug (wheel mappings were somehow influenced by the gamepad mappings). Updated the ticket accordingly.

**Comment by ChassyFlaps** [comment]
PCSX2 has seemed to have a serious regression with wheel support almost ALL games supporting the wheel have been completely broken eg: Enthusia the Feedback will just randomly give up at all times until you stop the car to get it back.Gran turismo 3 doesnt have any feedback at all. F1 the controls get supppper wonky. the only game i can get to run somewhat decently is gran turismo 4 but as of late even GT4 has displayed massive issues  with force feedback, Occasionally cutting out all feedback entirely. Also the amount of Force feedback related settings that were taken out of QT that likely wouldve given me the ability to fix these issues is beyond frustrating. Gran turismo 3 NEEDS an inverted FFB scheme but the option to do so has been taken out of the emulator while the plugin itself has these parameters

**Comment by refractionpcsx2** [comment]
If it upsets you, pull requests are welcome, this is an open source hobby project.

**Comment by ChassyFlaps** [comment]
Not upset giving to the best of my ability what i know about the issue. weird response

**Comment by ChassyFlaps** [comment]
Ill indeed do that. but ive been using QEMU for years and it really seems to be an issue on the emus end. while i do pull request i must ask is there any way to still access those parameters? whether it be through GUI of just a loose file ill even settle for an hour of converting floating points to HEX.

**Comment by refractionpcsx2** [comment]
A lot of the USB code was redone and uses SDL to access your controllers, so several options no longer exist.

**Comment by ChassyFlaps** [comment]
well that would definately explain alot, is there any plans for future implementation?

**Comment by refractionpcsx2** [comment]
As I said before `But we have limited access to devices for testing this stuff, so it's not really something we can fix` so it's not really something we have planned.
