### ISSUE TITLE
[META] Games which are CDVD Timing Sensitive

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#4117]
Some games seem to exhibit a behaviour where they do not function correctly if the CDVD is running at roughly the correct speed.  There seems to be no rhyme or reason to it, you can run the CDVD slower, or faster, and the game will work.

Looking at the IOP logs, everything seems to function normally, aside from when it reads the last interrupt, it acknowledges it, then never touches it again.  From playing around doing things like adjusting the VU timings or adjusting SIF timings seems to also change the issue, so I'm not sure if this is a game timing problem or a PCSX2 specific issue.

Games affected:

- [ ]  Digital Devil Saga (Hangs on certain cutscenes)
- [ ]  Silent Hill 2 (Hangs on certain cutscenes)
- [ ]  Shadowman 2 (Bad textures, prefers slower CDVD)

**Comment by seta-san** [comment]
doesn't ecco the dolphin and Victorious Boxers Ippo's Road to Victory both have issues with cdvd timing

-Ecco has an evil race condition: one of its custom IOP modules resets CDVDMAN while it's loading a module from disc. The race condition is resolved by making the EE slower. This gives enough time for CDVDMAN to reset itself before the EE sends a request to load a module.

-victorious boxers will hang unless you set "fast cdvd"

**Comment by refractionpcsx2** [comment]
Thanks, updated

**Comment by seta-san** [comment]
Bob the Builder locks on opening video without fast CDVD

**Comment by seta-san** [comment]
can we get checkmarks on bob, victorious, and shadowman and any others that we know are fixed?

**Comment by refractionpcsx2** [comment]
yeah Digital Devil Saga is fine now

**Comment by gilderoylockhart01** [comment]
Ecco the dolphin? Why is the game in that meta? Yeah, the game does stupid stings with the dvd driver, but I don't think it's directly a cdvd emulation problem.

**Comment by seta-san** [comment]
curious. if it's not a cdvd issue what kind of issue would it be ?

**Comment by HeroponRikiBestest** [comment]
According to https://www.patreon.com/posts/sins-of-ps2-ecco-38348208, it's an ee timing issue that just happens to cause a cdvd malfunction if it's not handled properly.

**Comment by JPTIZ** [comment]
About "Digital Devil Saga (Hangs on certain cutscenes)", I'm still having freezes after one of the last cutscenes (which didn't happen in some time ago, around 1 or 2 years). Specifically, my game freezes right after the end of this cutscene: https://www.youtube.com/watch?v=EJ9z0aiPRCw (specifically, there are two cutscenes that play in sequence - the one that freezes is the first one on the video, which ends in 2:38).

**Comment by refractionpcsx2** [comment]
it's known, you can turn on Fast CDVD (or possibly adjust the EE cycle rate, I forget) and that gets around.

**Comment by JPTIZ** [comment]
> it's known, you can turn on Fast CDVD (or possibly adjust the EE cycle rate, I forget) and that gets around.

Oh, you're right and it works! Thank you very much :)

**Comment by gitpro03** [comment]
Manhunt now works properly without fast CDVD.

**Comment by refractionpcsx2** [comment]
Thanks for letting me know :) Finding someone who could test it was a pain lol
