### ISSUE TITLE
Meta: Framebuffer Conversion Hack

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4849]
Games that have problem with textures corrupting or missing.

- [ ] Monster Lab
- [ ] Harry Potter and the Chamber of Secrets
- [x] Harry Potter and the Half-Blood Prince (seems unneeded as of latest 1.7)
- [x] Harry Potter and the Goblet of Fire (seems unneeded as of latest 1.7)
- [x] Harry Potter and the Order of the Phoenix (seems unneeded as of latest 1.7)
- [ ] Harry Potter and the Prisoner of Azkaban
- [x] Harry Potter and the Sorcerer's Stone (seems unneeded as of latest 1.7)
- [ ] Stuntman

**Comment by refractionpcsx2** [comment]
Stuntman as well to fix the broken textures, but it destroys the speed.

**Comment by gilderoylockhart01** [comment]
Spiderman 3 needs it but it will destroy the GS speed ald murder host vram.

**Comment by lightningterror** [comment]
Ideally we implement a proper solution and get rid of this nasty hack.

**Comment by kozarovv** [comment]
From hack comment `There is no dedicated shader to handle 4-bit conversion (Stuntman has been confirmed to use 4-bit).`

Why 4bit conversion on cpu is not default behavior? From what i understand handling that on gpu gonna fail now, and there is no alternative. 8 bit index based fb is different case because many times its proving to be fine on gpu shader, but since there is no way to handle 4 bit indexed stuff on gpu, maybe is worth to make that conversion to default to cpu?

**Comment by RedDevilus** [comment]
Think everything is (or will be) added.
