### ISSUE TITLE
Meta: Disc Swapping Capabilities

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4851]
Games that can use disc swapping to extend gameplay, unlock items, etc
Keep in mind disc swapping is broken at the moment.

- [x] SingStar Games (#3355) (Fixed in #4860)
- [x] Dual Disc Games (Linux Distro, God of War, Grandia 3, Xenosaga + others ) (Fixed in #4860)
- [x] Dragon Ball Z Budokai Tenkaichi 1/2 (+ others maybe) (Fixed in #4860)
- [x] Monster Rancher Games (EVO, 3, 4) (#3533) (Fixed in #4860)
- [x] Dynasty Warrior Games (#91) (Fixed in #4860)
- [x] Dance Factory (Fixed in #4860)
- [x] Singstar Take That (Annoying little gremlin)
- [x] Some versions of PS2 Linux, possibly

**Comment by RedDevilus** [comment]
Part 2 fixed by (SingStar Take That and PS2 Linux):
https://github.com/PCSX2/pcsx2/pull/5174
