### ISSUE TITLE
Meta: Auto Flush destroying performance

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#5081]
### Description

Games that tank performance when using autoflush (SW and HW). On SW it's enabled by default. On HW it's disabled by default.

- [ ] Alter Echo
- [ ] Need For Speed Underground 2
- [ ] Need For Speed Undercover
- [ ] Hitman Contracts
- [ ] Spider-Man: The Movie
- [ ] Powerdrome

### Reason

Better to have a tracker for games that don't like autoflush.

### Examples

Alter Echo;
SW autoflush: 42% (20.79)
SW no autofl: 250% (124.90)
Lost VPS = -208%  (-104.11)

![SWAutoFlushAlterEcho1](https://user-images.githubusercontent.com/24227051/143778389-1a37e824-0e1a-4315-8b43-9415f1a1642d.png)
![SWNoAutoFlushAlterEcho2](https://user-images.githubusercontent.com/24227051/143778398-f4fe401b-2e14-4043-bfd4-31684434e1ce.png)

8x HW autoflush: 86% (43.02)
8x HW no autofl: 154% (76.93)
Lost VPS = -68%  (-33.91)

![8xHWAutoFlushAlterEcho3](https://user-images.githubusercontent.com/24227051/143778407-b2b341a2-9699-4a3d-a97c-2b150583dfb3.png)
![8xHWNoAutoFlushAlterEcho4](https://user-images.githubusercontent.com/24227051/143778412-63a53c54-6850-4709-a3ff-94e680efbfdf.png)

**Comment by Satan86** [comment]
Need For Speed Underground 2 and Undercover also lose tonnes of FPS with Auto Flush
On
![image](https://user-images.githubusercontent.com/61447828/143788575-bce68b16-bddd-4a1d-b221-54ade00de29f.png)
![image](https://user-images.githubusercontent.com/61447828/143788788-7f04bb18-0028-4a3c-90c0-4ef7ef7025cc.png)

Off
![image](https://user-images.githubusercontent.com/61447828/143788582-d1f55e18-05ab-47a9-8875-6def8ab15e1b.png)
![image](https://user-images.githubusercontent.com/61447828/143788874-32962c0a-d8cf-4aef-8b95-435fa086d978.png)
This is on Software mode

**Comment by gilderoylockhart01** [comment]
There are several games where autoflush is super slow on hardware but fast on software, which is... weird.

**Comment by RedDevilus** [comment]
Tested on 1.7.2415;

old SW autoflush: 42% (20.79) [Last year Q4]
old SW no autofl: 250% (124.90) [Last year Q4]
new SW autoflush: 210% (104.87) [As of writing 6th march 2022]
Lost VPS = -40% (-20.03)

This games used to tank over -200% instead of -40% less VPS if you use autoflush while still substantial, this was the worst hitting game in my collection. Quite a victory I would say, was even questioning if I had autoflush on :P

SW with autoflush:
![image](https://user-images.githubusercontent.com/24227051/156908163-c07ae07c-9a73-48a9-87a2-8bdbdb467c1c.png)

**Comment by refractionpcsx2** [comment]
As far as I see it, you're still 40fps above 60fps, so there's a bit of give in there at least, and only losing 20fps is nothing really.

**Comment by RedDevilus** [comment]
Kinda crazy how it used to be less than half the VPS to be full speed now.
