### ISSUE TITLE
Meta: Vertex trace overflow

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#5137]
### Description

Some games have floating math problems where it goes beyond the scope that PCSX2 should handle:

- [ ] Primal (Seems fixed by using non-default rounding and clamping) 
- [ ] Galerians Ash
- [ ] Valkyrie Profile 2
- [ ] Street Fighter 3 EX
- [ ] Evil Dead: Regeneration

### Reason

Track vertex trace overflow

### Examples

What to look out for in the Program Log is this message:
 `Vertex Trace: float overflow detected ! min 3.402823e+38 max 3.402823e+38`

**Comment by noigeaR** [comment]
>     * [ ]  Disney's Up (Not confirmed)
Disney Pixar's Up throws the "Vertex Trace: float overflow" error even when you only run a single frame GS dump. I think the status can be changed to confirmed.

[gs_20220702133822_Disney Pixar - Up_SLUS-21864.zip](https://github.com/PCSX2/pcsx2/files/9126231/gs_20220702133822_Disney.Pixar.-.Up_SLUS-21864.zip)

The range is smaller in the GS dump.
Vertex Trace: float overflow detected ! min 3.191373e+34 max 6.488020e+35
But I also get min 3.402823e+38 max 3.402823e+38 during the intro like Danke-Boi reported.

The subtitle rendering problem reported in #4761 is still in 1.7.3082, but depending on the Texture Preloading setting it may behave differently. Since issue #4761 was closed, I'll add my findings here.

What the subtitles are supposed to look like (software mode)
![gs_20220702172250_Disney Pixar - Up_SLUS-21864](https://user-images.githubusercontent.com/2962364/179364664-94c26593-b297-477d-a198-198c4c6ec652.png)

The subtitles are completely invisible with Texture Preloading set to Partial or Full (Hash Cache) in hardware mode
![gs_20220702172255_Disney Pixar - Up_SLUS-21864](https://user-images.githubusercontent.com/2962364/179364774-8289075a-7679-468c-b97b-2bf227a749f6.png)

The subtitles appear grey and unreadable with Texture Preloading set to none (hardware mode)
![gs_20220702133822_Disney Pixar - Up_SLUS-21864](https://user-images.githubusercontent.com/2962364/179364851-5c41b5a0-294c-4271-9065-91bb8f21a7fb.png)

The subtitles aren't always the same shade of grey though. If you load the GS Dump provided above and switch between software and hardware multiple times, the subtitles are sometimes bright grey, sometimes dark grey and sometimes they are completely invisible. It seems to depend on the timing when switching from software to hardware mode. With Texture Preloading enabled the subtitles are always invisible.

**Comment by MrCK1** [comment]
Overflow in Cold Winter occurs in pause menu background (SW). Still active as of 1.7.4871

`[   17.5230] Vertex Trace: float overflow detected ! min 3.402823e+38 max 3.402823e+38`

**Comment by TheTechnician27** [comment]
Overflow occurs in both SpongeBob SquarePants: Revenge of the Flying Dutchman (prevents the camera lock sprite from showing) and in Spider-Man: The Movie (with no obvious negative effect).

**Comment by RedPanda4552** [comment]
@danielb4150 piracy is not supported here.
