### ISSUE TITLE
Meta: GSdx PCRTC issues

### ISSUE THREAD

**Issue by rz5** [PCSX2/pcsx2#961]
The documentation of the GS states that frame buffer width can be obtained by multiplying the value of FBW (a field of the FRAME register) by 64.
Frame buffer height isn't specified in registers; the documentation says the height on the PS2 is to be controlled with scissoring tests.

Right now pcsx2 relies on hacks and guesses, including:
0) Display height is good for every game except for Pool Paradise, which sets DH to 1151
when the proper value should be 576;
1) Frame buffer height is roughly the same height as display (DH + 1 / MAGH +1),
unless it's DMC3 or the US/JP version of SkyGunner - then the height gets set to 448 and it
may be halved if the game is interlaced + frame mode
2) "Device" height is the same as display height, unless it's interlaced + frame mode - then
the current height gets halved.

There are still some games where the hacks/guesses in the codebase don't work, where the height is still not correct and we get black bars on the bottom of the screen or the picture.

Ideally there would be a way to detect and set the correct height solely based the state of registers that the GS is able to see.
- **List of _known_ PCRTC issues**
- [ ] [KOF 2000](http://forums.pcsx2.net/Thread-GSDX-PCRTC-Bug-Report-The-King-of-Fighters-2000-SLPS-251-56) `(improper height)`
- [ ] Metal Slug 3 `(improper height)` (NTSC 60hz only)
- [ ] Twisted Metal FMV `(improper width)`
- [ ] ICO FMV `(improper width)`

Possible
- [ ] Virtua Figher 4 - https://forums.pcsx2.net/Thread-Virtua-Fighter-4-SCES-50759-E--30477?pid=612849#pid612849

**Comment by mirhl** [comment]
Improved by #962

**Comment by gregory38** [comment]
To complete the information:
* Framebuffer size is independent of the real display size.
* Scissor only impact the rendering in the Framebuffer
* Pool paradise uses 16 bits formats, height are 2 times bigger with 16 bits format.

**Comment by rz5** [comment]
@gregory38 had an idea about NTSC mode resolutions having a maximum height of 448. #962 changes GSState.cpp::GetFrameRect() to test this idea and it seems to work.

**Comment by gregory38** [comment]
Thanks for the credits ^^ However I don't know if it a real physical limitation (speed of the PLL), potentially some NTSC games can use a bigger resolution.

**Comment by rz5** [comment]
I'm quoting @ramapcsx2 on this: 
"@sudonim1 and me spent a couple weeks actively trying to force a fix for all this"
"it failed because gsdx was missing a couple other gs features that would also have to be added and working"
"(...) scissoring is involved"
"(...) and that feature that allows games to reposition the image on the screen"

**Comment by ramapcsx2** [comment]
@gregory38 You won't find any games exploiting any higher resolution. So good call on that :p

**Comment by gregory38** [comment]
@ramapcsx2 see #1013

**Comment by rz5** [comment]
Ensuring NTSC video mode has a max height of 448 seems to fix some games (DMC3 at 60Hz, SkyGunner and Tribes: Aerial Assault) but in turn breaks the PlayStation 2 logo when doing File > Boot CDVD (full). See issue #1054

**Comment by mirh** [comment]
So.. is this fixed now? After #1416 or #1433 perhaps?

**Comment by rz5** [comment]
I dunno, have we discovered the black magic formula that allows us to calculate the height of a frame?

**Comment by mirh** [comment]
I would sure hope those, together with #1234 did it.

**Comment by ssakash** [comment]
No, it's not _properly_ fixed yet. I tried to find some kind of general formula for the output circuit dimensions by logging all the GS registers value but still I wasn't able to find anything useful.

The issue is with games providing wrong value on their DISP registers. ( Tribes: Aerial Assault for example)

**Comment by MrCK1** [comment]
@ssakash Do we want to make a metapost with games that still have wrong height values? I know of a few that have this issue

**Comment by ssakash** [comment]
> Do we want to make a metapost with games that still have wrong height values?

A meta post for CRTC specific issues would be nice. IIRC [KOF 2000](http://forums.pcsx2.net/Thread-GSDX-PCRTC-Bug-Report-The-King-of-Fighters-2000-SLPS-251-56) still has height related issues even with NTSC saturation hack, however height detection isn't the only issue on PCRTC circuit, some games also get the width of the output circuit wrong (Twisted Metal FMV's for example)

![twmetal](http://i.imgur.com/vBcE3rB.png)

**Note**: ``(Notice the black border on right side)``, FWIW saturating the width to 640 instead of 720 seems to fix the issue. Potentially it's a limitation on the PLL when NTSC colorburst is detected on the real hardware. All of these issues could be easily fixed with CRC hacks but I prefer finding a accurate solution instead.

Currently all I can assume is that, these games are sending buggy values to the display registers and that the original hardware must be correcting it somehow to produce proper output with respect to the video mode. So yeah, always nice to keep track of such games. :)

I'm focusing right now on the games which need the NTSC saturation hack, just trying to figure out any other accurate alternative by analyzing the register states.

**Comment by rz5** [comment]
@ssakash, glad to see you still fighting the good fight about height. I re-read my comments on this thread to get a refresher. I'm gonna start pinging names:

@ramapcsx2 @sudonim1 - Do you remember what GS-related features GSDX doesn't emulate that might be related to this?

@jpd002 - You've most likely stumbled upon this problem too. How are you handling it? Per-game hacks like pcsx2 had before or are you in search of the golden GS height formula as well?

**Comment by ssakash** [comment]
> You've most likely stumbled upon this problem too. How are you handling it? 

FWIW Play! also seems to suffer from all these CRTC issues the last time I looked at it.

**Comment by jpd002** [comment]
@rz5 @ssakash Not doing anything to handle problematic cases at the moment. I haven't done much work on getting it to work properly either. I was planning on doing some tests on real hardware to see how the registers change what we see on the CRT.

**Comment by MrCK1** [comment]
Went through a few games, DR detection needs refinement. I'll check more tomorrow when I'm back on my desktop ;)
- GH2 is 640x447 during FMV playback, thin line on bottom
- ATV Offroad Fury - runs at 639 x 448, output looks fine however
- Evo SB - runs at 512x441

The two that I'm positive have CRTC issues are Jonny Moseley Mad Trix and IR (I really need to check IR on hardware)

JMMT (pic is old, I'll get height values tomorrow) 

![gsdx_20160625205338](https://cloud.githubusercontent.com/assets/16314399/19712602/3dd1624e-9b0d-11e6-8af8-6d733c5e2a89.png)
IR - game is claiming to be running at 640 x 480 during FMVs, rest of game runs at 640x478 and picture unstable (not interlacing problem, text kerning offset as well)
![gsdx_20161025234113](https://cloud.githubusercontent.com/assets/16314399/19712514/96e31bb2-9b0c-11e6-8707-e9626e4cbadd.png)

**Comment by ssakash** [comment]
Could you provide a GS dump of the FMV issues on ``Jonny Moseley Mad Trix`` and ``Iridium Runners``? Potentially they're not related to the display rectangle setup.

On the other hand, FMV issues on twisted metal and ICO seem to have something in common. They use a _high_ DW value (2879) on NTSC/PAL modes whereas the normal value is (2559) which is used by all NTSC/PAL video modes, saturating the value to the normal one seems to fix the issue but _probably_ not the right fix.

**Comment by FlatOutPS2** [comment]
I think I know another game. Kengo, which has a black bar at the top instead of bottom.

**Comment by MrCK1** [comment]
@ssakash I'll post the GS dumps tomorrow

**Comment by FlatOutPS2** [comment]
> Here's the dumps for JMMT and Iridium Runners. 

@MrCK1 Can you reupload those dumps? It seems filedropper uploads are only available for a few weeks.

**Comment by MrCK1** [comment]
Here's the dumps, 3 weeks late :p (rename .pdf to .zip)

[JMMT and IR Dumps.pdf](https://github.com/PCSX2/pcsx2/files/680158/JMMT.and.IR.Dumps.pdf)

**Comment by FlatOutPS2** [comment]
@MrCK1 Thanks. Three weeks late is still less than I was too late in trying to download 'em in the first place. ;)

**Comment by MrCK1** [comment]
@ssakash I have found another case that may be similar to the issue with JMMT. The Suffering has this issue where the output switches from 448x640 to 640x494 when viewing TV monitors in-game. The bouncing image you see in the .gif is the HW renderer output (other is SW). Changing interlacing settings either didn't work or stabilized the image with varying degrees of ghosting.

Here's the [GS Dumps](https://github.com/PCSX2/pcsx2/files/695187/TheSuffering_TTB_GSDump.pdf) from both renderers (change .pdf to .7z)

![](https://media.giphy.com/media/xYbEYD7O9UWWY/giphy.gif)

**Comment by ssakash** [comment]
Does ``Preload data frame`` fix the issue? It seems to fix it when replaying from the GSDump GUI. If that doesn't fix it then could you check whether the issue is present on 1.4?

**Comment by MrCK1** [comment]
```Preload frame data``` didn't work for me. In 1.4, normal game height was 640x447 and changed to 448 when viewing the monitors, but no problems (and it's in color :p) A half-screen issue is also present in certain sequences is present in both 1.4 and latest git, so I'll ask to get it added to the list.

![gsdx_20170110013931](https://cloud.githubusercontent.com/assets/16314399/21796393/80f3eae2-d6d6-11e6-8bde-f5fef45cc594.png)

**Comment by FlatOutPS2** [comment]
> Does Preload data frame fix the issue? It seems to fix it when replaying from the GSDump GUI. If that doesn't fix it then could you check whether the issue is present on 1.4?

Don't rely on any result you get from the Preload Frame Data hack in a GS Dump. It gives false results 99% of the time.

**Comment by MrCK1** [comment]
@ssakash  https://github.com/PCSX2/pcsx2/commit/8fecd3512ccc86bcc4c23f5f8431a01c61b0b34f (dev-1744) introduced the regression in The Suffering that was causing the wrong display height and issues when viewing monitors

The earliest GSdx build (dev-1742) before the regression was introduced had none of the problems mentioned above and the width/height shows the correct value instead of 640x494 in dev-1744 to the latest git builds.

**Comment by FlatOutPS2** [comment]
@MrCK1 1744 didn't introduce the issue, it just returned it to it's original behaviour.

This issue does not appear to be a PCRTC issue at all. The screen is fine in Software mode, in Direct3D Hardware the screen it's stretched beyond the bottom of the screen(this used to be the case for OGL HW too), and in OpenGL Hardware it does this flickering/stretching.

**Comment by MrCK1** [comment]
@FlatOutPS2 
I brushed over the code last week, but I've found some time to revisit this. As usual, you were spot on 😃  

In the commit you linked, the addition of feedback write to the merge circuit causes StretchRect to toggle back and forth in a loop, that was causing the picture to flicker. Here's the results I got from the merge circuit (I removed some extranenous info) before and after the regression was introduced.

Pre-regression
```
 EID  | Event                                                                | Draw #
---------------------------------------------------------------------------------------
      | - Renderer Merge 22245                                               | 1     
      |  \- DoMerge                                                          | 1     
      |    \- Clear RT 214                                                   | 1     
      |     - StretchRect from 79 to 214                                     | 2
      | - Present                                                            | 3     
      |  \- Clear RT 0                                                       | 3     
      |   - StretchRect from 214 to 0                                        | 4     
37    |   - SwapBuffers()                                                    | 5     
```

Post-regression
```
 EID  | Event                                                                | Draw #
---------------------------------------------------------------------------------------
      | - Renderer Merge 35299                                               | 1     
      |  \- DoMerge                                                          | 1     
      |    \- Clear RT 215                                                   | 1     
      |     - StretchRect from 1 to 215                                      | 2        
      |     - StretchRect from 215 to 1                                      | 3       
      |     - Clear RT 215                                                   | 4     
      |     - StretchRect from 1 to 215                                      | 5
      | - Present                                                            | 6     
      |  \- Clear RT 0                                                       | 6     
      |   - StretchRect from 215 to 0                                        | 7     
59    |   - SwapBuffers()                                                    | 8     
```

**Comment by Silanda** [comment]
SNK vs Capcom: SVC Chaos (PAL), is another game that seems to be affected by this issue and has a black bar at the bottom of the screen. As I understand the code, since the width of output resolution is 640 pixels (640x512), it fails the unsupported resolution test in #1866 and that fix is not applied. 

Currently I'm using a custom build to apply CRC based fixes to KoF2000 (on the 2000/2001 double pack) and SVC Chaos, though that's not ideal.

**Comment by Silanda** [comment]
Another game that could possibly be added here is the PAL version of Deus Ex. 

The gameplay and menus are fine, but the loading screens are cut off at the bottom (the loading bar is off screen). The game appears to call for a height of 896, and as the Pool Paradise height fix halves the vertical resolution, this results in an output of 640x448. It needs to be 640x512. 

I've added a hack in my build to address this specific case, but I don't think that's a great solution.

**Comment by MrCK1** [comment]
Added Virtual Fighter 4 as another possible game to look into (has black bar at bottom of screen in PAL)
